/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vehler;

import java.awt.Color;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import oracle.jdbc.OracleTypes;

/**
 *
 * @author user
 */
public class AddVehicle extends javax.swing.JFrame {

    /**
     * Creates new form AdminPage
     */
  String model,version,plateNo,color,RDate,EDate,carName,username;
  Vehicle v;
  public AddVehicle()
  {
      
  }
    public AddVehicle(String username) {
      
        initComponents();
        this.username=username;
     
       
        getfromltol("{call getfromltol(?)}");
        gettime("{call gettime(?)}");
//          fromLabel.setVisible(false);
//        toLabel.setVisible(false);
//        busRoute.setVisible(false);
//        fromCombo.setVisible(false);
//        toCombo.setVisible(false);
//        doneButton.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        registerPlateNo = new javax.swing.JTextField();
        registerCarName = new javax.swing.JTextField();
        finishButton = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel36 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel37 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel39 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        addVehicleButton = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        removeVehicleButton = new javax.swing.JPanel();
        addVehicleButton5 = new javax.swing.JPanel();
        Adddriver = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        settingsButton = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        logOutButton = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        banDriverButton2 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        banDriverButton3 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        banDriverButton4 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        addVehicleButton1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Adddriver1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Adddriver2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        jMenu6.setText("jMenu6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(5, 5));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 666));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 102, 102));
        jLabel24.setText("Plate No");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 237, -1, -1));

        jLabel27.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(102, 102, 102));
        jLabel27.setText("Vehicle Name");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 294, -1, -1));

        registerPlateNo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        registerPlateNo.setForeground(new java.awt.Color(102, 102, 102));
        registerPlateNo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        jPanel1.add(registerPlateNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 235, 260, 20));

        registerCarName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        registerCarName.setForeground(new java.awt.Color(102, 102, 102));
        registerCarName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        jPanel1.add(registerCarName, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 284, 259, -1));

        finishButton.setBackground(new java.awt.Color(255, 255, 255));
        finishButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 102, 255), 3));
        finishButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                finishButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                finishButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                finishButtonMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Add");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout finishButtonLayout = new javax.swing.GroupLayout(finishButton);
        finishButton.setLayout(finishButtonLayout);
        finishButtonLayout.setHorizontalGroup(
            finishButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(finishButtonLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        finishButtonLayout.setVerticalGroup(
            finishButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, finishButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jPanel1.add(finishButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 560, -1, -1));

        jLabel29.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(102, 102, 102));
        jLabel29.setText("Sessions");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));

        jLabel1.setText("Bus");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 182, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Session 1", "Session 2", " " }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, -1));

        jLabel36.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(102, 102, 102));
        jLabel36.setText("Type");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 179, -1, -1));

        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 230, -1));

        jPanel1.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, 230, -1));

        jPanel1.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 460, 230, -1));

        jLabel37.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(102, 102, 102));
        jLabel37.setText("From");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, -1, -1));

        jLabel25.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 102, 102));
        jLabel25.setText("To");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, -1, -1));

        jLabel38.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(102, 102, 102));
        jLabel38.setText("Departure Time");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, -1, -1));

        jPanel1.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 510, 230, -1));

        jLabel39.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(102, 102, 102));
        jLabel39.setText("Arrival Time");
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 1060, 770));

        jPanel3.setBackground(new java.awt.Color(51, 0, 102));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Vehler");

        addVehicleButton.setBackground(new java.awt.Color(51, 0, 102));
        addVehicleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addVehicleButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addVehicleButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addVehicleButtonMouseExited(evt);
            }
        });
        addVehicleButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Add Bus");
        addVehicleButton.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Transportation_25px.png"))); // NOI18N
        addVehicleButton.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 57, 30));

        removeVehicleButton.setBackground(new java.awt.Color(51, 0, 102));
        removeVehicleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                removeVehicleButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                removeVehicleButtonMouseExited(evt);
            }
        });
        removeVehicleButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addVehicleButton5.setBackground(new java.awt.Color(51, 0, 102));
        addVehicleButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addVehicleButton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addVehicleButton5MouseExited(evt);
            }
        });
        addVehicleButton5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        removeVehicleButton.add(addVehicleButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Adddriver.setBackground(new java.awt.Color(51, 0, 102));
        Adddriver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdddriverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AdddriverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AdddriverMouseExited(evt);
            }
        });
        Adddriver.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(240, 240, 240));
        jLabel12.setText("Add Driver");
        Adddriver.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 80, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Denied_25px.png"))); // NOI18N
        Adddriver.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 57, 30));

        settingsButton.setBackground(new java.awt.Color(51, 0, 102));
        settingsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settingsButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                settingsButtonMouseExited(evt);
            }
        });
        settingsButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(240, 240, 240));
        jLabel18.setText("More");
        settingsButton.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Settings_25px.png"))); // NOI18N
        settingsButton.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 57, 30));

        logOutButton.setBackground(new java.awt.Color(51, 0, 102));
        logOutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logOutButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logOutButtonMouseExited(evt);
            }
        });
        logOutButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(240, 240, 240));
        jLabel20.setText("Log Out");
        logOutButton.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Logout_Rounded_Up_25px.png"))); // NOI18N
        logOutButton.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 57, 30));

        banDriverButton2.setBackground(new java.awt.Color(51, 0, 102));
        banDriverButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                banDriverButton2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                banDriverButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                banDriverButton2MouseExited(evt);
            }
        });
        banDriverButton2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(240, 240, 240));
        jLabel26.setText("Ban Driver");
        banDriverButton2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Denied_25px.png"))); // NOI18N
        banDriverButton2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 57, 30));

        banDriverButton3.setBackground(new java.awt.Color(51, 0, 102));
        banDriverButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                banDriverButton3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                banDriverButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                banDriverButton3MouseExited(evt);
            }
        });
        banDriverButton3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(240, 240, 240));
        jLabel28.setText("Ban Bus");
        banDriverButton3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Denied_25px.png"))); // NOI18N
        banDriverButton3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 57, 30));

        banDriverButton4.setBackground(new java.awt.Color(51, 0, 102));
        banDriverButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                banDriverButton4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                banDriverButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                banDriverButton4MouseExited(evt);
            }
        });
        banDriverButton4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(240, 240, 240));
        jLabel30.setText("Ban Passenger");
        banDriverButton4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Denied_25px.png"))); // NOI18N
        banDriverButton4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 57, 30));

        addVehicleButton1.setBackground(new java.awt.Color(51, 0, 102));
        addVehicleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addVehicleButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addVehicleButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addVehicleButton1MouseExited(evt);
            }
        });
        addVehicleButton1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Home");
        addVehicleButton1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        Adddriver1.setBackground(new java.awt.Color(51, 0, 102));
        Adddriver1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Adddriver1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Adddriver1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Adddriver1MouseExited(evt);
            }
        });
        Adddriver1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(240, 240, 240));
        jLabel15.setText("Add Route");
        Adddriver1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 80, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Denied_25px.png"))); // NOI18N
        Adddriver1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 57, 30));

        Adddriver2.setBackground(new java.awt.Color(51, 0, 102));
        Adddriver2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Adddriver2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Adddriver2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Adddriver2MouseExited(evt);
            }
        });
        Adddriver2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(240, 240, 240));
        jLabel17.setText("Add Time");
        Adddriver2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 80, 30));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Denied_25px.png"))); // NOI18N
        Adddriver2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 57, 30));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addVehicleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(removeVehicleButton, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                    .addComponent(settingsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logOutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Adddriver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(banDriverButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(banDriverButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(banDriverButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addVehicleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Adddriver1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Adddriver2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel5))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(addVehicleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(addVehicleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Adddriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Adddriver1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Adddriver2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(banDriverButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(banDriverButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(banDriverButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(settingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(logOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(removeVehicleButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 780));

        setSize(new java.awt.Dimension(1408, 770));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 public void gettime(String query)
   {
       AddVehicle av=new AddVehicle();
       
   String sql=query;
   try
  {
       Connection1 cc=new Connection1();
             Connection con=cc.setconnection();
      Statement s=con.createStatement();
    CallableStatement stmt = con.prepareCall("{call gettime(?)}"); 
     stmt.registerOutParameter(1,OracleTypes.CURSOR);

            stmt.execute();
  ResultSet rs = (ResultSet) stmt.getObject(1);
    while(rs.next())
            {
               String a=(rs.getString("ARRIVALTIME")); 
               String b=(rs.getString("DEPARTURETIME"));
                jComboBox4.addItem(a);
                jComboBox5.addItem(b);
                
           }
    System.out.println("Stored Procedure executed successfully");
  }
  catch(Exception err)
  {
    System.out.println("An error has occurred.");
    System.out.println("See full details below.");
    err.printStackTrace();
  }

       
       
   }
   public void getfromltol(String query)
   {
       AddVehicle av=new AddVehicle();
       
   String sql=query;
   try
  {
       Connection1 cc=new Connection1();
             Connection con=cc.setconnection();
      Statement s=con.createStatement();
    CallableStatement stmt = con.prepareCall("{call getfromltol(?)}"); 
     stmt.registerOutParameter(1,OracleTypes.CURSOR);

            stmt.execute();
  ResultSet rs = (ResultSet) stmt.getObject(1);
    while(rs.next())
            {
                String a=(rs.getString("FROML"));
                
               String b=(rs.getString("TOL"));
                jComboBox2.addItem(a);
                jComboBox3.addItem(b);
                 
           }
    System.out.println("Stored Procedure executed successfully");
  }
  catch(Exception err)
  {
    System.out.println("An error has occurred.");
    System.out.println("See full details below.");
    err.printStackTrace();
  }
       
   }
  
    
    private void finishButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_finishButtonMouseEntered
        // TODO add your handling code here:
        finishButton.setBackground(new Color(153,102,255));
        jLabel2.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_finishButtonMouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseExited

    private void finishButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_finishButtonMouseExited
        // TODO add your handling code here:
        finishButton.setBackground(new Color(255,255,255));
        jLabel2.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_finishButtonMouseExited

    private void finishButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_finishButtonMouseClicked
        // TODO add your handling code here:
        
        if(registerCarName.getText().equals("")||registerPlateNo.getText().equals(""))
{
    JOptionPane.showMessageDialog(null,"Please fill All Fields");
}
        if(jComboBox2.getSelectedItem().equals("")||jComboBox5.getSelectedItem().equals("")||jComboBox4.getSelectedItem().equals("")||jComboBox5.getSelectedItem().equals(""))
        {
             JOptionPane.showMessageDialog(null,"Please Enter Route Or Time First");
        }
//else if(checkCar.isSelected()==false&&checkRickshaw.isSelected()==false&&checkBus.isSelected()==false)
//{
//    JOptionPane.showMessageDialog(null,"Please fill All Fields");
//}
else 
{
    
   plateNo=registerPlateNo.getText();
   carName=registerCarName.getText();
   String status="0";
   int s;
   String session=(String)jComboBox1.getSelectedItem();
   if(session.equals("Session 1"))
   {
        s=1;
   }
   else{
       s=2;
   }
   String from=(String)jComboBox2.getSelectedItem();
   String to=(String)jComboBox3.getSelectedItem();
   String arrival=(String)jComboBox4.getSelectedItem();
   String depart=(String)jComboBox5.getSelectedItem();
   
   Admin a=new Admin();
  boolean chk= a.insertbusdata("{call insertbus(?,?,?,?,?,?,?,?)}", plateNo, carName, status,s,from,to,arrival,depart);
//  boolean chk=a.insertbusdata("Insert into BUS (BUS,BUSNAME,STATUS) values (' "+ plateNo+ "','"+ carName+ "','" + status+ "')");
    if(chk)
    {
          JOptionPane.showMessageDialog(null,"Van Added Succesfully!!!");
          registerPlateNo.setText("");
          registerCarName.setText("");
    }
    else{
         JOptionPane.showMessageDialog(null,"Van Already Exist");
    }
//    String type = null;
//    type="Car";
//    if(checkCar.isSelected())
//    {
//        type=checkCar.getText();
//    }
//    else if(checkBus.isSelected())
//    {
//        type=checkBus.getText();
//    }
//    else if(checkRickshaw.isSelected())
//    {
//        type=checkRickshaw.getText();
//    }
//     v=new Vehicle(model,version,color,plateNo,RDate,EDate);
//    if(type=="Car")
//    {
//        Car car=new Car(v.getModel(),v.getVersion(),v.getColor(),v.getPlateNo(),v.getregistrationDate(),v.getExpirationDate(),carName);
//        car.addCar();
//        registerPlateNo.setText("");
//
//        registerCarName.setText("");
//        
//    }
 
//    else if(type=="Rickshaw")
//    {
//        Rickshaw rickshaw=new Rickshaw(v.getModel(),v.getVersion(),v.getColor(),v.getPlateNo(),v.getregistrationDate(),v.getExpirationDate(),carName);
//        rickshaw.addRickshaw();
//        registerModel.setText("");
//        registerVersion.setText("");
//        registerColor.setText("");
//        registerPlateNo.setText("");
//  
//        registerCarName.setText("");
//    }
}
    }//GEN-LAST:event_finishButtonMouseClicked

    private void addVehicleButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addVehicleButtonMouseClicked
        // TODO add your handling code here:
      
    }//GEN-LAST:event_addVehicleButtonMouseClicked

    private void addVehicleButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addVehicleButtonMouseEntered
        // TODO add your handling code here:
        addVehicleButton.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_addVehicleButtonMouseEntered

    private void addVehicleButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addVehicleButtonMouseExited
        // TODO add your handling code here:
        addVehicleButton.setBackground(new Color(51,0,102));
    }//GEN-LAST:event_addVehicleButtonMouseExited

    private void addVehicleButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addVehicleButton5MouseEntered
        // TODO add your handling code here:
        addVehicleButton5.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_addVehicleButton5MouseEntered

    private void addVehicleButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addVehicleButton5MouseExited
        // TODO add your handling code here:
        addVehicleButton5.setBackground(new Color(51,0,102));
    }//GEN-LAST:event_addVehicleButton5MouseExited

    private void removeVehicleButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeVehicleButtonMouseEntered
        // TODO add your handling code here:
        removeVehicleButton.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_removeVehicleButtonMouseEntered

    private void removeVehicleButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeVehicleButtonMouseExited
        // TODO add your handling code here:
        removeVehicleButton.setBackground(new Color(51,0,102));
    }//GEN-LAST:event_removeVehicleButtonMouseExited

    private void AdddriverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdddriverMouseClicked
        // TODO add your handling code here:
        Admin a=new Admin();
        boolean chk=a.checkbusavail();
        if(chk){
            this.setVisible(false);
            RegistrationFormd reg=new RegistrationFormd();
            reg.setVisible(true);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Cannot Add Driver When NO Bus Is Available");
        }
    }//GEN-LAST:event_AdddriverMouseClicked

    private void AdddriverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdddriverMouseEntered
        // TODO add your handling code here:
        Adddriver.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_AdddriverMouseEntered

    private void AdddriverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdddriverMouseExited
        // TODO add your handling code here:
        Adddriver.setBackground(new Color(51,0,102));
    }//GEN-LAST:event_AdddriverMouseExited

    private void settingsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsButtonMouseClicked
        // TODO add your handling code here:
        More as=new More(username);
        this.setVisible(false);
        as.setVisible(true);
    }//GEN-LAST:event_settingsButtonMouseClicked

    private void settingsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsButtonMouseEntered
        // TODO add your handling code here:
        settingsButton.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_settingsButtonMouseEntered

    private void settingsButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsButtonMouseExited
        // TODO add your handling code here:
        settingsButton.setBackground(new Color(51,0,102));
    }//GEN-LAST:event_settingsButtonMouseExited

    private void logOutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutButtonMouseClicked
        // TODO add your handling code here:
        LoginMain lm=new LoginMain();
        this.setVisible(false);
        lm.setVisible(true);
    }//GEN-LAST:event_logOutButtonMouseClicked

    private void logOutButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutButtonMouseEntered
        // TODO add your handling code here:
        logOutButton.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_logOutButtonMouseEntered

    private void logOutButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutButtonMouseExited
        // TODO add your handling code here:
        logOutButton.setBackground(new Color(51,0,102));
    }//GEN-LAST:event_logOutButtonMouseExited

    private void banDriverButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_banDriverButton2MouseClicked
        // TODO add your handling code here:
        BanDriver bd=new BanDriver(username);
        this.hide();
        bd.show();

    }//GEN-LAST:event_banDriverButton2MouseClicked

    private void banDriverButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_banDriverButton2MouseEntered
        // TODO add your handling code here:
        banDriverButton2.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_banDriverButton2MouseEntered

    private void banDriverButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_banDriverButton2MouseExited
        // TODO add your handling code here:
        banDriverButton2.setBackground(new Color(51,0,102));
    }//GEN-LAST:event_banDriverButton2MouseExited

    private void banDriverButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_banDriverButton3MouseClicked
        // TODO add your handling code here:
        Banbus bd=new Banbus(username);
        this.hide();
        bd.show();

    }//GEN-LAST:event_banDriverButton3MouseClicked

    private void banDriverButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_banDriverButton3MouseEntered
        // TODO add your handling code here:
        banDriverButton3.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_banDriverButton3MouseEntered

    private void banDriverButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_banDriverButton3MouseExited
        // TODO add your handling code here:
        banDriverButton3.setBackground(new Color(51,0,102));
    }//GEN-LAST:event_banDriverButton3MouseExited

    private void banDriverButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_banDriverButton4MouseClicked
        // TODO add your handling code here:
        Banpassenger bd=new Banpassenger(username);
        this.hide();
        bd.show();
    }//GEN-LAST:event_banDriverButton4MouseClicked

    private void banDriverButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_banDriverButton4MouseEntered
        // TODO add your handling code here:
        banDriverButton4.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_banDriverButton4MouseEntered

    private void banDriverButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_banDriverButton4MouseExited
        // TODO add your handling code here:
        banDriverButton4.setBackground(new Color(51,0,102));
    }//GEN-LAST:event_banDriverButton4MouseExited

    private void addVehicleButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addVehicleButton1MouseClicked
        // TODO add your handling code here:
        AdminHome av=new AdminHome(username);
        this.setVisible(false);
        av.setVisible(true);
    }//GEN-LAST:event_addVehicleButton1MouseClicked

    private void addVehicleButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addVehicleButton1MouseEntered
        // TODO add your handling code here:
        addVehicleButton1.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_addVehicleButton1MouseEntered

    private void addVehicleButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addVehicleButton1MouseExited
        // TODO add your handling code here:
        addVehicleButton1.setBackground(new Color(51,0,102));
    }//GEN-LAST:event_addVehicleButton1MouseExited

    private void Adddriver1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Adddriver1MouseClicked
        // TODO add your handling code here:
        Addroute av=new Addroute(username);
        this.setVisible(false);
        av.setVisible(true);
    }//GEN-LAST:event_Adddriver1MouseClicked

    private void Adddriver1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Adddriver1MouseEntered
        // TODO add your handling code here:
        Adddriver1.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_Adddriver1MouseEntered

    private void Adddriver1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Adddriver1MouseExited
        // TODO add your handling code here:
        Adddriver1.setBackground(new Color(51,0,102));
    }//GEN-LAST:event_Adddriver1MouseExited

    private void Adddriver2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Adddriver2MouseClicked
        // TODO add your handling code here:
        Addtime aa=new Addtime(username);
        this.hide();
        aa.show();
    }//GEN-LAST:event_Adddriver2MouseClicked

    private void Adddriver2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Adddriver2MouseEntered
        // TODO add your handling code here:
          Adddriver2.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_Adddriver2MouseEntered

    private void Adddriver2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Adddriver2MouseExited
        // TODO add your handling code here:
         Adddriver2.setBackground(new Color(51,0,102));
    }//GEN-LAST:event_Adddriver2MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddVehicle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Adddriver;
    private javax.swing.JPanel Adddriver1;
    private javax.swing.JPanel Adddriver2;
    private javax.swing.JPanel addVehicleButton;
    private javax.swing.JPanel addVehicleButton1;
    private javax.swing.JPanel addVehicleButton5;
    private javax.swing.JPanel banDriverButton2;
    private javax.swing.JPanel banDriverButton3;
    private javax.swing.JPanel banDriverButton4;
    private javax.swing.JPanel finishButton;
    private javax.swing.JComboBox<String> jComboBox1;
    public javax.swing.JComboBox<String> jComboBox2;
    public javax.swing.JComboBox<String> jComboBox3;
    public javax.swing.JComboBox<String> jComboBox4;
    public javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel logOutButton;
    private javax.swing.JTextField registerCarName;
    private javax.swing.JTextField registerPlateNo;
    private javax.swing.JPanel removeVehicleButton;
    private javax.swing.JPanel settingsButton;
    // End of variables declaration//GEN-END:variables
}
