package vehler;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class AdminHome extends javax.swing.JFrame {

    /**
     * Creates new form AdminHome
     */
    private String username;
    public AdminHome()
    {
        
    }
    public AdminHome(String username) {
        this.username=username;
        initComponents();
        Ride r=new Ride();
        if(r.attchk==1)
        {
         attendancebtn.hide();
         absent1.hide();
        absent2.hide();
        absent3.hide();
        absent4.hide();
        absent5.hide();
        absent6.hide();
        absent7.hide();
        absent8.hide();
        f1.hide();
        f2.hide();
        f3.hide();
        f4.hide();
        f5.hide();
        f6.hide();
        f7.hide();
        f8.hide();
        jLabel8.hide();
        saveattendance.hide();
        Admin a=new Admin();
        a.gettabdata("{call schudata(?)}", admintab);
        }
        absent1.hide();
        absent2.hide();
        absent3.hide();
        absent4.hide();
        absent5.hide();
        absent6.hide();
        absent7.hide();
        absent8.hide();
        f1.hide();
        f2.hide();
        f3.hide();
        f4.hide();
        f5.hide();
        f6.hide();
        f7.hide();
        f8.hide();
        jLabel8.hide();
        saveattendance.hide();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        addVehicleButton = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        removeVehicleButton = new javax.swing.JPanel();
        addVehicleButton5 = new javax.swing.JPanel();
        Adddriver = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        settingsButton = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        logOutButton = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        banDriverButton2 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        banDriverButton3 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        banDriverButton4 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        addVehicleButton1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Adddriver1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Adddriver2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        attendancebtn = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        admintab = new javax.swing.JTable();
        absent5 = new javax.swing.JPanel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        absent1 = new javax.swing.JPanel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        absent6 = new javax.swing.JPanel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        absent2 = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        absent3 = new javax.swing.JPanel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        absent4 = new javax.swing.JPanel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        absent7 = new javax.swing.JPanel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        absent8 = new javax.swing.JPanel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        saveattendance = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        f1 = new javax.swing.JTextField();
        f2 = new javax.swing.JTextField();
        f3 = new javax.swing.JTextField();
        f4 = new javax.swing.JTextField();
        f5 = new javax.swing.JTextField();
        f6 = new javax.swing.JTextField();
        f7 = new javax.swing.JTextField();
        f8 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 102, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Admin Control Room");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Welcome");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Hamza Ansari");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator2)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(632, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 1110, 150));

        jPanel3.setBackground(new java.awt.Color(51, 0, 102));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Vehler");

        addVehicleButton.setBackground(new java.awt.Color(51, 0, 102));
        addVehicleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addVehicleButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addVehicleButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addVehicleButtonMouseExited(evt);
            }
        });
        addVehicleButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Add Bus");
        addVehicleButton.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Transportation_25px.png"))); // NOI18N
        addVehicleButton.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 57, 30));

        removeVehicleButton.setBackground(new java.awt.Color(51, 0, 102));
        removeVehicleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                removeVehicleButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                removeVehicleButtonMouseExited(evt);
            }
        });
        removeVehicleButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addVehicleButton5.setBackground(new java.awt.Color(51, 0, 102));
        addVehicleButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addVehicleButton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addVehicleButton5MouseExited(evt);
            }
        });
        addVehicleButton5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        removeVehicleButton.add(addVehicleButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Adddriver.setBackground(new java.awt.Color(51, 0, 102));
        Adddriver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdddriverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AdddriverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AdddriverMouseExited(evt);
            }
        });
        Adddriver.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(240, 240, 240));
        jLabel12.setText("Add Driver");
        Adddriver.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 80, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Denied_25px.png"))); // NOI18N
        Adddriver.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 57, 30));

        settingsButton.setBackground(new java.awt.Color(51, 0, 102));
        settingsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settingsButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                settingsButtonMouseExited(evt);
            }
        });
        settingsButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(240, 240, 240));
        jLabel18.setText("More");
        settingsButton.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Settings_25px.png"))); // NOI18N
        settingsButton.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 57, 30));

        logOutButton.setBackground(new java.awt.Color(51, 0, 102));
        logOutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logOutButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logOutButtonMouseExited(evt);
            }
        });
        logOutButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(240, 240, 240));
        jLabel20.setText("Log Out");
        logOutButton.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Logout_Rounded_Up_25px.png"))); // NOI18N
        logOutButton.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 57, 30));

        banDriverButton2.setBackground(new java.awt.Color(51, 0, 102));
        banDriverButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                banDriverButton2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                banDriverButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                banDriverButton2MouseExited(evt);
            }
        });
        banDriverButton2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(240, 240, 240));
        jLabel26.setText("Ban Driver");
        banDriverButton2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Denied_25px.png"))); // NOI18N
        banDriverButton2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 57, 30));

        banDriverButton3.setBackground(new java.awt.Color(51, 0, 102));
        banDriverButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                banDriverButton3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                banDriverButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                banDriverButton3MouseExited(evt);
            }
        });
        banDriverButton3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(240, 240, 240));
        jLabel28.setText("Ban Bus");
        banDriverButton3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Denied_25px.png"))); // NOI18N
        banDriverButton3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 57, 30));

        banDriverButton4.setBackground(new java.awt.Color(51, 0, 102));
        banDriverButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                banDriverButton4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                banDriverButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                banDriverButton4MouseExited(evt);
            }
        });
        banDriverButton4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(240, 240, 240));
        jLabel30.setText("Ban Passenger");
        banDriverButton4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Denied_25px.png"))); // NOI18N
        banDriverButton4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 57, 30));

        addVehicleButton1.setBackground(new java.awt.Color(51, 0, 102));
        addVehicleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addVehicleButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addVehicleButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addVehicleButton1MouseExited(evt);
            }
        });
        addVehicleButton1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Home");
        addVehicleButton1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        Adddriver1.setBackground(new java.awt.Color(51, 0, 102));
        Adddriver1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Adddriver1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Adddriver1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Adddriver1MouseExited(evt);
            }
        });
        Adddriver1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(240, 240, 240));
        jLabel15.setText("Add Route");
        Adddriver1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 80, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Denied_25px.png"))); // NOI18N
        Adddriver1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 57, 30));

        Adddriver2.setBackground(new java.awt.Color(51, 0, 102));
        Adddriver2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Adddriver2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Adddriver2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Adddriver2MouseExited(evt);
            }
        });
        Adddriver2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(240, 240, 240));
        jLabel17.setText("Add Time");
        Adddriver2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 80, 30));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Denied_25px.png"))); // NOI18N
        Adddriver2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 57, 30));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addVehicleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(removeVehicleButton, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE))
                    .addComponent(settingsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logOutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Adddriver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(banDriverButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(banDriverButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(banDriverButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addVehicleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Adddriver1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Adddriver2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(addVehicleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(addVehicleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Adddriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Adddriver1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Adddriver2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(banDriverButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(banDriverButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(banDriverButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(settingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(logOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(removeVehicleButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 760));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 0, 102));
        jLabel14.setText("A wide range of controls in your hands.");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 640, -1, 50));

        attendancebtn.setBackground(new java.awt.Color(153, 51, 255));
        attendancebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attendancebtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                attendancebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                attendancebtnMouseExited(evt);
            }
        });
        attendancebtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 204, 204));
        jLabel22.setText("Mark Attendance");
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        attendancebtn.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel2.add(attendancebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 170, 40));

        admintab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Session", "BusNo", "From", "To", "Time", "Driver Name", "Driver ID", "Attendance"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        admintab.setRowHeight(28);
        admintab.setSelectionBackground(new java.awt.Color(51, 0, 102));
        admintab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                admintabMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(admintab);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 740, 320));

        absent5.setBackground(new java.awt.Color(153, 51, 255));
        absent5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                absent5MouseClicked(evt);
            }
        });
        absent5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel57.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(204, 204, 204));
        jLabel57.setText("EMAIL");
        absent5.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));

        jLabel58.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(204, 204, 204));
        jLabel58.setText("Absent");
        jLabel58.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel58MouseClicked(evt);
            }
        });
        absent5.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 40, 20));

        jPanel2.add(absent5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 400, 100, 20));

        absent1.setBackground(new java.awt.Color(153, 51, 255));
        absent1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                absent1MouseClicked(evt);
            }
        });
        absent1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel59.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(204, 204, 204));
        jLabel59.setText("EMAIL");
        absent1.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));

        jLabel60.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(204, 204, 204));
        jLabel60.setText("Absent");
        jLabel60.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel60MouseClicked(evt);
            }
        });
        absent1.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 20));

        jPanel2.add(absent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 280, 100, 20));

        absent6.setBackground(new java.awt.Color(153, 51, 255));
        absent6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                absent6MouseClicked(evt);
            }
        });
        absent6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel61.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(204, 204, 204));
        jLabel61.setText("EMAIL");
        absent6.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));

        jLabel62.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(204, 204, 204));
        jLabel62.setText("Absent");
        jLabel62.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel62MouseClicked(evt);
            }
        });
        absent6.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 40, 20));

        jPanel2.add(absent6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 430, 100, 20));

        absent2.setBackground(new java.awt.Color(153, 51, 255));
        absent2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                absent2MouseClicked(evt);
            }
        });
        absent2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel63.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(204, 204, 204));
        jLabel63.setText("EMAIL");
        absent2.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));

        jLabel64.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(204, 204, 204));
        jLabel64.setText("Absent");
        jLabel64.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel64MouseClicked(evt);
            }
        });
        absent2.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 40, 20));

        jPanel2.add(absent2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 310, 100, 20));

        absent3.setBackground(new java.awt.Color(153, 51, 255));
        absent3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                absent3MouseClicked(evt);
            }
        });
        absent3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel65.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(204, 204, 204));
        jLabel65.setText("EMAIL");
        absent3.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));

        jLabel66.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(204, 204, 204));
        jLabel66.setText("Absent");
        jLabel66.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel66MouseClicked(evt);
            }
        });
        absent3.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 40, 20));

        jPanel2.add(absent3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 340, 100, 20));

        absent4.setBackground(new java.awt.Color(153, 51, 255));
        absent4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                absent4MouseClicked(evt);
            }
        });
        absent4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel67.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(204, 204, 204));
        jLabel67.setText("EMAIL");
        absent4.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));

        jLabel68.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(204, 204, 204));
        jLabel68.setText("Absent");
        jLabel68.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel68MouseClicked(evt);
            }
        });
        absent4.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 40, 20));

        jPanel2.add(absent4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 370, 100, 20));

        absent7.setBackground(new java.awt.Color(153, 51, 255));
        absent7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                absent7MouseClicked(evt);
            }
        });
        absent7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel69.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(204, 204, 204));
        jLabel69.setText("EMAIL");
        absent7.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));

        jLabel70.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(204, 204, 204));
        jLabel70.setText("Absent");
        jLabel70.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel70MouseClicked(evt);
            }
        });
        absent7.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 40, 20));

        jPanel2.add(absent7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 460, 100, 20));

        absent8.setBackground(new java.awt.Color(153, 51, 255));
        absent8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                absent8MouseClicked(evt);
            }
        });
        absent8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel71.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(204, 204, 204));
        jLabel71.setText("EMAIL");
        absent8.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));

        jLabel72.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(204, 204, 204));
        jLabel72.setText("Absent");
        jLabel72.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel72MouseClicked(evt);
            }
        });
        absent8.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 40, 20));

        jPanel2.add(absent8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 490, 100, 20));

        saveattendance.setBackground(new java.awt.Color(153, 51, 255));
        saveattendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveattendanceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saveattendanceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saveattendanceMouseExited(evt);
            }
        });
        saveattendance.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 204, 204));
        jLabel23.setText("EMAIL");
        saveattendance.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));

        jLabel24.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(204, 204, 204));
        jLabel24.setText("Save");
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });
        saveattendance.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jPanel2.add(saveattendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 590, 110, 40));

        f1.setText("Enter Alternative Driver");
        f1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                f1FocusGained(evt);
            }
        });
        f1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f1ActionPerformed(evt);
            }
        });
        jPanel2.add(f1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 280, 170, -1));

        f2.setText("Enter Alternative Driver");
        f2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                f2FocusGained(evt);
            }
        });
        jPanel2.add(f2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 310, 170, -1));

        f3.setText("Enter Alternative Driver");
        f3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                f3FocusGained(evt);
            }
        });
        jPanel2.add(f3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 340, 170, -1));

        f4.setText("Enter Alternative Driver");
        f4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                f4FocusGained(evt);
            }
        });
        jPanel2.add(f4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 370, 170, -1));

        f5.setText("Enter Alternative Driver");
        f5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                f5FocusGained(evt);
            }
        });
        jPanel2.add(f5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 400, 170, -1));

        f6.setText("Enter Alternative Driver");
        f6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                f6FocusGained(evt);
            }
        });
        jPanel2.add(f6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 430, 170, -1));

        f7.setText("Enter Alternative Driver");
        f7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                f7FocusGained(evt);
            }
        });
        jPanel2.add(f7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 460, 170, -1));

        f8.setText("Enter Alternative Driver");
        f8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                f8FocusGained(evt);
            }
        });
        jPanel2.add(f8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 490, 170, -1));

        jLabel32.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(51, 0, 102));
        jLabel32.setText("Make it happen.");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 670, -1, 50));

        jLabel8.setText("Enter Alternative Driver");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 220, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1452, 761));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addVehicleButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addVehicleButtonMouseEntered
        // TODO add your handling code here:
        addVehicleButton.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_addVehicleButtonMouseEntered

    private void addVehicleButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addVehicleButtonMouseExited
        // TODO add your handling code here:
        addVehicleButton.setBackground(new Color(51,0,102));
    }//GEN-LAST:event_addVehicleButtonMouseExited

    private void AdddriverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdddriverMouseEntered
        // TODO add your handling code here:
        Adddriver.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_AdddriverMouseEntered

    private void AdddriverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdddriverMouseExited
        // TODO add your handling code here:
         Adddriver.setBackground(new Color(51,0,102));
    }//GEN-LAST:event_AdddriverMouseExited

    private void settingsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsButtonMouseEntered
        // TODO add your handling code here:
        settingsButton.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_settingsButtonMouseEntered

    private void settingsButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsButtonMouseExited
        // TODO add your handling code here:
         settingsButton.setBackground(new Color(51,0,102));
    }//GEN-LAST:event_settingsButtonMouseExited

    private void logOutButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutButtonMouseEntered
        // TODO add your handling code here:
        logOutButton.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_logOutButtonMouseEntered

    private void logOutButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutButtonMouseExited
        // TODO add your handling code here:
         logOutButton.setBackground(new Color(51,0,102));
    }//GEN-LAST:event_logOutButtonMouseExited

    private void removeVehicleButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeVehicleButtonMouseExited
        // TODO add your handling code here:
        removeVehicleButton.setBackground(new Color(51,0,102));
    }//GEN-LAST:event_removeVehicleButtonMouseExited

    private void removeVehicleButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeVehicleButtonMouseEntered
        // TODO add your handling code here:
        removeVehicleButton.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_removeVehicleButtonMouseEntered

    private void addVehicleButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addVehicleButton5MouseExited
        // TODO add your handling code here:
         addVehicleButton5.setBackground(new Color(51,0,102));
    }//GEN-LAST:event_addVehicleButton5MouseExited

    private void addVehicleButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addVehicleButton5MouseEntered
        // TODO add your handling code here:
         addVehicleButton5.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_addVehicleButton5MouseEntered

    private void addVehicleButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addVehicleButtonMouseClicked
        // TODO add your handling code here:
        AddVehicle av=new AddVehicle(username);
        this.setVisible(false);
        av.setVisible(true);
    }//GEN-LAST:event_addVehicleButtonMouseClicked

    private void AdddriverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdddriverMouseClicked
        // TODO add your handling code here:
    Admin a=new Admin();
    boolean chk=a.checkbusavail();
    if(chk){
        this.setVisible(false);
        RegistrationFormd reg=new RegistrationFormd();
        reg.setVisible(true);
    }
    else
    {
        JOptionPane.showMessageDialog(null, "Cannot Add Driver When NO Bus Is Available");
    }
    }//GEN-LAST:event_AdddriverMouseClicked

    private void settingsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsButtonMouseClicked
        // TODO add your handling code here:
        More as=new More(username);
        this.setVisible(false);
        as.setVisible(true);
    }//GEN-LAST:event_settingsButtonMouseClicked

    private void logOutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutButtonMouseClicked
        // TODO add your handling code here:
        LoginMain lm=new LoginMain();
        this.setVisible(false);
        lm.setVisible(true);
        
    }//GEN-LAST:event_logOutButtonMouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        // TODO add your handling code here:
   jLabel8.show();
     Admin aa=new Admin();
     Ride r=new Ride();
     if(r.attchk==0){
     aa.gettabdata("{call schdata(?)}", admintab);
     }
     else
     {
          aa.gettabdata("{call schudata(?)}", admintab);
     }
 
     
//     aa.gettabdata("SELECT s.SID,s.bus,r.froml,r.tol,t.arrivaltime,d.dname,d.did,s.attendance from schedule s join sessions ss on s.sid=ss.sid \n" +
//"join routes r on r.rid=ss.rid join times t on t.tid=ss.tid join driver.drivers d on d.did=s.did", admintab);
  
      int a=admintab.getRowCount();
//        System.out.println(a);
      saveattendance.show();
        switch(a){
            case 1:
                //System.out.println("asdas");
                f1.setText(admintab.getValueAt(0, 2).toString());
              absent1.show(); 
              break;
            case 2:
                 f1.setText(admintab.getValueAt(0, 2).toString());
                  f2.setText(admintab.getValueAt(1, 2).toString());
                absent1.show();
                absent2.show(); break;
            case 3:
                f1.setText(admintab.getValueAt(0, 2).toString());
                  f2.setText(admintab.getValueAt(1, 2).toString());
                   f3.setText(admintab.getValueAt(2, 2).toString());
                 absent1.show();
                absent2.show();
              absent3.show();  break;
            case 4:
                 f1.setText(admintab.getValueAt(0, 2).toString());
                  f2.setText(admintab.getValueAt(1, 2).toString());
                   f3.setText(admintab.getValueAt(2, 2).toString());
                    f4.setText(admintab.getValueAt(3, 2).toString());
                   absent1.show();
                absent2.show();
              absent3.show(); 
                absent4.show(); break;
            case 5:
                  f1.setText(admintab.getValueAt(0, 2).toString());
                  f2.setText(admintab.getValueAt(1, 2).toString());
                   f3.setText(admintab.getValueAt(2,2).toString());
                    f4.setText(admintab.getValueAt(3, 2).toString());
                     f5.setText(admintab.getValueAt(4, 2).toString());
                absent1.show();
                absent2.show();
              absent3.show(); 
                absent4.show();
              absent5.show();  break;
            case 6:
                  f1.setText(admintab.getValueAt(0, 2).toString());
                  f2.setText(admintab.getValueAt(1, 2).toString());
                   f3.setText(admintab.getValueAt(2, 2).toString());
                    f4.setText(admintab.getValueAt(3, 2).toString());
                     f5.setText(admintab.getValueAt(4, 2).toString());
                      f6.setText(admintab.getValueAt(5, 2).toString());
                absent1.show();
                absent2.show();
              absent3.show(); 
                absent4.show();
                absent5.show(); 
                absent6.show(); break;
            case 7:
                   f1.setText(admintab.getValueAt(0, 2).toString());
                  f2.setText(admintab.getValueAt(1, 2).toString());
                   f3.setText(admintab.getValueAt(2, 2).toString());
                    f4.setText(admintab.getValueAt(3, 2).toString());
                     f5.setText(admintab.getValueAt(4, 2).toString());
                      f6.setText(admintab.getValueAt(5, 2).toString());
                        f7.setText(admintab.getValueAt(6, 2).toString());
                absent1.show();
                absent2.show();
              absent3.show(); 
                absent4.show();
                absent5.show(); 
                absent6.show();
              absent7.show();  break;
            case 8:
                  f1.setText(admintab.getValueAt(0, 6).toString());
                  f2.setText(admintab.getValueAt(1, 6).toString());
                   f3.setText(admintab.getValueAt(2, 6).toString());
                    f4.setText(admintab.getValueAt(3, 6).toString());
                     f5.setText(admintab.getValueAt(4, 6).toString());
                      f6.setText(admintab.getValueAt(5, 6).toString());
                        f7.setText(admintab.getValueAt(6, 6).toString());
                          f8.setText(admintab.getValueAt(7, 6).toString());
                 absent1.show();
                absent2.show();
              absent3.show(); 
                absent4.show();
                absent5.show(); 
                absent6.show();
              absent7.show(); 
                absent8.show(); break;
            default:
            { saveattendance.hide();}
        }

   
    
//        attendancebtn.action(null,null);
    }//GEN-LAST:event_jLabel22MouseClicked

    private void attendancebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendancebtnMouseClicked
        // TODO add your handling code here:
    jLabel8.show();
     Admin aa=new Admin();
     Ride r=new Ride();
     if(r.attchk==0){
     aa.gettabdata("{call schdata(?)}", admintab);
     }
     else
     {
          aa.gettabdata("{call schudata(?)}", admintab);
     }
 
     
//     aa.gettabdata("SELECT s.SID,s.bus,r.froml,r.tol,t.arrivaltime,d.dname,d.did,s.attendance from schedule s join sessions ss on s.sid=ss.sid \n" +
//"join routes r on r.rid=ss.rid join times t on t.tid=ss.tid join driver.drivers d on d.did=s.did", admintab);
  
      int a=admintab.getRowCount();
//        System.out.println(a);
      saveattendance.show();
        switch(a){
            case 1:
                //System.out.println("asdas");
                f1.setText(admintab.getValueAt(0, 2).toString());
              absent1.show(); 
              break;
            case 2:
                 f1.setText(admintab.getValueAt(0, 2).toString());
                  f2.setText(admintab.getValueAt(1, 2).toString());
                absent1.show();
                absent2.show(); break;
            case 3:
                f1.setText(admintab.getValueAt(0, 2).toString());
                  f2.setText(admintab.getValueAt(1, 2).toString());
                   f3.setText(admintab.getValueAt(2, 2).toString());
                 absent1.show();
                absent2.show();
              absent3.show();  break;
            case 4:
                 f1.setText(admintab.getValueAt(0, 2).toString());
                  f2.setText(admintab.getValueAt(1, 2).toString());
                   f3.setText(admintab.getValueAt(2, 2).toString());
                    f4.setText(admintab.getValueAt(3, 2).toString());
                   absent1.show();
                absent2.show();
              absent3.show(); 
                absent4.show(); break;
            case 5:
                  f1.setText(admintab.getValueAt(0, 2).toString());
                  f2.setText(admintab.getValueAt(1, 2).toString());
                   f3.setText(admintab.getValueAt(2,2).toString());
                    f4.setText(admintab.getValueAt(3, 2).toString());
                     f5.setText(admintab.getValueAt(4, 2).toString());
                absent1.show();
                absent2.show();
              absent3.show(); 
                absent4.show();
              absent5.show();  break;
            case 6:
                  f1.setText(admintab.getValueAt(0, 2).toString());
                  f2.setText(admintab.getValueAt(1, 2).toString());
                   f3.setText(admintab.getValueAt(2, 2).toString());
                    f4.setText(admintab.getValueAt(3, 2).toString());
                     f5.setText(admintab.getValueAt(4, 2).toString());
                      f6.setText(admintab.getValueAt(5, 2).toString());
                absent1.show();
                absent2.show();
              absent3.show(); 
                absent4.show();
                absent5.show(); 
                absent6.show(); break;
            case 7:
                   f1.setText(admintab.getValueAt(0, 2).toString());
                  f2.setText(admintab.getValueAt(1, 2).toString());
                   f3.setText(admintab.getValueAt(2, 2).toString());
                    f4.setText(admintab.getValueAt(3, 2).toString());
                     f5.setText(admintab.getValueAt(4, 2).toString());
                      f6.setText(admintab.getValueAt(5, 2).toString());
                        f7.setText(admintab.getValueAt(6, 2).toString());
                absent1.show();
                absent2.show();
              absent3.show(); 
                absent4.show();
                absent5.show(); 
                absent6.show();
              absent7.show();  break;
            case 8:
                  f1.setText(admintab.getValueAt(0, 6).toString());
                  f2.setText(admintab.getValueAt(1, 6).toString());
                   f3.setText(admintab.getValueAt(2, 6).toString());
                    f4.setText(admintab.getValueAt(3, 6).toString());
                     f5.setText(admintab.getValueAt(4, 6).toString());
                      f6.setText(admintab.getValueAt(5, 6).toString());
                        f7.setText(admintab.getValueAt(6, 6).toString());
                          f8.setText(admintab.getValueAt(7, 6).toString());
                 absent1.show();
                absent2.show();
              absent3.show(); 
                absent4.show();
                absent5.show(); 
                absent6.show();
              absent7.show(); 
                absent8.show(); break;
            default:
            { saveattendance.hide();}
        }

    }//GEN-LAST:event_attendancebtnMouseClicked

    private void attendancebtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendancebtnMouseEntered
        // TODO add your handling code here:
        attendancebtn.setBackground(new Color(204,153,255));
    }//GEN-LAST:event_attendancebtnMouseEntered

    private void attendancebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendancebtnMouseExited
        // TODO add your handling code here:
        attendancebtn.setBackground(new Color(153,51,255));
    }//GEN-LAST:event_attendancebtnMouseExited

    private void admintabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admintabMouseClicked
        // TODO add your handling code here:
     

    }//GEN-LAST:event_admintabMouseClicked

    private void jLabel58MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel58MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel58MouseClicked

    private void absent5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_absent5MouseClicked
        // TODO add your handling code here:
        f5.show();
       
    }//GEN-LAST:event_absent5MouseClicked

    private void jLabel60MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel60MouseClicked
        // TODO add your handling code here:
        f6.show();
    }//GEN-LAST:event_jLabel60MouseClicked

    private void absent1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_absent1MouseClicked
        // TODO add your handling code here:
        f1.show();
    }//GEN-LAST:event_absent1MouseClicked

    private void jLabel62MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel62MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel62MouseClicked

    private void absent6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_absent6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_absent6MouseClicked

    private void jLabel64MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel64MouseClicked
        // TODO add your handling code here:
        f6.show();
    }//GEN-LAST:event_jLabel64MouseClicked

    private void absent2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_absent2MouseClicked
        // TODO add your handling code here:
        f2.show();
    }//GEN-LAST:event_absent2MouseClicked

    private void jLabel66MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel66MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel66MouseClicked

    private void absent3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_absent3MouseClicked
        // TODO add your handling code here:
        f3.show();
    }//GEN-LAST:event_absent3MouseClicked

    private void jLabel68MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel68MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel68MouseClicked

    private void absent4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_absent4MouseClicked
        // TODO add your handling code here:
        f4.show();
    }//GEN-LAST:event_absent4MouseClicked

    private void jLabel70MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel70MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel70MouseClicked

    private void absent7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_absent7MouseClicked
        // TODO add your handling code here:
        f7.show();
    }//GEN-LAST:event_absent7MouseClicked

    private void jLabel72MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel72MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel72MouseClicked

    private void absent8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_absent8MouseClicked
        // TODO add your handling code here:
        f8.show();
    }//GEN-LAST:event_absent8MouseClicked

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel24MouseClicked

    private void saveattendanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveattendanceMouseClicked
        // TODO add your handling code here:
        
        Admin a=new Admin();
        a.deldt();
       
//        if((f1.equals("")||f1.equals("Enter Alternative Driver"))&&(f2.equals("")||f2.equals("Enter Alternative Driver"))&&(f3.equals("")||f3.equals("Enter Alternative Driver"))
//                &&(f4.equals("")||f4.equals("Enter Alternative Driver"))&&(f5.equals("")||f5.equals("Enter Alternative Driver"))&&(f6.equals("")||f6.equals("Enter Alternative Driver"))
//                &&(f7.equals("")||f7.equals("Enter Alternative Driver"))&&(f8.equals("")||f8.equals("Enter Alternative Driver")))
//       if((f1.equals("")||f1.equals("Enter Alternative Driver")||f1.isVisible()==false)&&
//          (f2.equals("")||f2.equals("Enter Alternative Driver")||f2.isVisible()==false)&&
//          (f3.equals("")||f3.equals("Enter Alternative Driver")||f3.isVisible()==false)&&
//               (f4.equals("")||f4.equals("Enter Alternative Driver")||f4.isVisible()==false)&&
//               (f5.equals("")||f5.equals("Enter Alternative Driver")||f5.isVisible()==false)&&
//               (f6.equals("")||f6.equals("Enter Alternative Driver")||f6.isVisible()==false)&&
//               (f7.equals("")||f7.equals("Enter Alternative Driver")||f7.isVisible()==false)&&
//               (f8.equals("")||f8.equals("Enter Alternative Driver")||f8.isVisible()==false))
{
        for(int i=0;i<admintab.getRowCount();i++)
        {
             String d="";
           String s=admintab.getValueAt(i, 0).toString();
           String b=admintab.getValueAt(i, 1).toString();
           if(i==0)
           {
               d=f1.getText().toString();
           }
            if(i==1)
           {
              d=f2.getText().toString();
           }
             if(i==2)
           {
                d=f3.getText().toString();
           }
              if(i==3)
           {
               d=f4.getText().toString();
           }
               if(i==4)
           {
                d=f5.getText().toString();
           }
                if(i==5)
           {
                d=f6.getText().toString();
           }
                 if(i==6)
           {
             d=f7.getText().toString();
           }
                  if(i==7)
           {
                d=f8.getText().toString();
           }
           
           
           
           
           
           //String d=admintab.getValueAt(i, 6).toString();
           String at=admintab.getValueAt(i, 4).toString();
           int ss=Integer.parseInt(s);
           try{
              
           int dd=Integer.parseInt(d);
             a.udata("{call scheduleENTER(?,?,?,?)}", ss, dd, b, at);
            
              
      
        //  a.gettabupdata("call schdata(?)", admintab);
              
           }
           catch(Exception e)
           {
                JOptionPane.showMessageDialog(null, "Please Enter Correct DID");
           }
         }
         JOptionPane.showMessageDialog(null, "Attendance Saved");
              Admin aa=new Admin();
             Ride r=new Ride();
             r.attchk=1;
//              for(int ik=0;i<admintab.getColumnCount();i++)
//              {
//                  admintab.remo
//              }
             a.gettabupdata("call schudata(?)", admintab);
             if(r.attchk==1)
        {
         attendancebtn.hide();
         absent1.hide();
        absent2.hide();
        absent3.hide();
        absent4.hide();
        absent5.hide();
        absent6.hide();
        absent7.hide();
        absent8.hide();
        f1.hide();
        f2.hide();
        f3.hide();
        f4.hide();
        f5.hide();
        f6.hide();
        f7.hide();
        f8.hide();
        jLabel8.hide();
        saveattendance.hide();
    
        }
        
        }
       
         
        
        
        
        
        
        
        
    }//GEN-LAST:event_saveattendanceMouseClicked

    private void saveattendanceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveattendanceMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_saveattendanceMouseEntered

    private void saveattendanceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveattendanceMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_saveattendanceMouseExited

    private void f1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_f1FocusGained
        // TODO add your handling code here:
        f1.setText("");
    }//GEN-LAST:event_f1FocusGained

    private void f2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_f2FocusGained
        // TODO add your handling code here:
        f2.setText("");
    }//GEN-LAST:event_f2FocusGained

    private void f3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_f3FocusGained
        // TODO add your handling code here:
        f3.setText("");
    }//GEN-LAST:event_f3FocusGained

    private void f4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_f4FocusGained
        // TODO add your handling code here:
        f4.setText("");
    }//GEN-LAST:event_f4FocusGained

    private void f5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_f5FocusGained
        // TODO add your handling code here:
        f5.setText("");
    }//GEN-LAST:event_f5FocusGained

    private void f6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_f6FocusGained
        // TODO add your handling code here:
        f6.setText("");
    }//GEN-LAST:event_f6FocusGained

    private void f7FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_f7FocusGained
        // TODO add your handling code here:
        f7.setText("");
    }//GEN-LAST:event_f7FocusGained

    private void f8FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_f8FocusGained
        // TODO add your handling code here:
        f8.setText("");
    }//GEN-LAST:event_f8FocusGained

    private void banDriverButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_banDriverButton2MouseClicked
        // TODO add your handling code here:
        BanDriver bd=new BanDriver(username);
        this.hide();
        bd.show();
        
        
    }//GEN-LAST:event_banDriverButton2MouseClicked

    private void banDriverButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_banDriverButton2MouseEntered
        // TODO add your handling code here:
         banDriverButton2.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_banDriverButton2MouseEntered

    private void banDriverButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_banDriverButton2MouseExited
        // TODO add your handling code here:
                 banDriverButton2.setBackground(new Color(51,0,102));

    }//GEN-LAST:event_banDriverButton2MouseExited

    private void banDriverButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_banDriverButton3MouseClicked
        // TODO add your handling code here:
          Banbus bd=new Banbus(username);
        this.hide();
        bd.show();
         
    }//GEN-LAST:event_banDriverButton3MouseClicked

    private void banDriverButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_banDriverButton3MouseEntered
        // TODO add your handling code here:
        banDriverButton3.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_banDriverButton3MouseEntered

    private void banDriverButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_banDriverButton3MouseExited
        // TODO add your handling code here:
                 banDriverButton3.setBackground(new Color(51,0,102));

    }//GEN-LAST:event_banDriverButton3MouseExited

    private void banDriverButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_banDriverButton4MouseClicked
        // TODO add your handling code here:
       Banpassenger bd=new Banpassenger(username);
        this.hide();
        bd.show();
    }//GEN-LAST:event_banDriverButton4MouseClicked

    private void banDriverButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_banDriverButton4MouseEntered
        // TODO add your handling code here:
         banDriverButton4.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_banDriverButton4MouseEntered

    private void banDriverButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_banDriverButton4MouseExited
        // TODO add your handling code here:
                 banDriverButton4.setBackground(new Color(51,0,102));

    }//GEN-LAST:event_banDriverButton4MouseExited

    private void addVehicleButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addVehicleButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addVehicleButton1MouseClicked

    private void addVehicleButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addVehicleButton1MouseEntered
        // TODO add your handling code here:
         addVehicleButton1.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_addVehicleButton1MouseEntered

    private void addVehicleButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addVehicleButton1MouseExited
        // TODO add your handling code here:
        addVehicleButton1.setBackground(new Color(51,0,102));
    }//GEN-LAST:event_addVehicleButton1MouseExited

    private void Adddriver1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Adddriver1MouseClicked
        // TODO add your handling code here:
         Addroute av=new Addroute(username);
        this.setVisible(false);
        av.setVisible(true);
    }//GEN-LAST:event_Adddriver1MouseClicked

    private void Adddriver1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Adddriver1MouseEntered
        // TODO add your handling code here:
         Adddriver1.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_Adddriver1MouseEntered

    private void Adddriver1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Adddriver1MouseExited
        // TODO add your handling code here:
         Adddriver1.setBackground(new Color(51,0,102));
    }//GEN-LAST:event_Adddriver1MouseExited

    private void Adddriver2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Adddriver2MouseClicked
        // TODO add your handling code here:
        Addtime aa=new Addtime(username);
        this.hide();
        aa.show();
    }//GEN-LAST:event_Adddriver2MouseClicked

    private void Adddriver2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Adddriver2MouseEntered
        // TODO add your handling code here:
        Adddriver2.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_Adddriver2MouseEntered

    private void Adddriver2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Adddriver2MouseExited
        // TODO add your handling code here:
        Adddriver2.setBackground(new Color(51,0,102));
    }//GEN-LAST:event_Adddriver2MouseExited

    private void f1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Adddriver;
    private javax.swing.JPanel Adddriver1;
    private javax.swing.JPanel Adddriver2;
    private javax.swing.JPanel absent1;
    private javax.swing.JPanel absent2;
    private javax.swing.JPanel absent3;
    private javax.swing.JPanel absent4;
    private javax.swing.JPanel absent5;
    private javax.swing.JPanel absent6;
    private javax.swing.JPanel absent7;
    private javax.swing.JPanel absent8;
    private javax.swing.JPanel addVehicleButton;
    private javax.swing.JPanel addVehicleButton1;
    private javax.swing.JPanel addVehicleButton5;
    private javax.swing.JTable admintab;
    private javax.swing.JPanel attendancebtn;
    private javax.swing.JPanel banDriverButton2;
    private javax.swing.JPanel banDriverButton3;
    private javax.swing.JPanel banDriverButton4;
    private javax.swing.JTextField f1;
    private javax.swing.JTextField f2;
    private javax.swing.JTextField f3;
    private javax.swing.JTextField f4;
    private javax.swing.JTextField f5;
    private javax.swing.JTextField f6;
    private javax.swing.JTextField f7;
    private javax.swing.JTextField f8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel logOutButton;
    private javax.swing.JPanel removeVehicleButton;
    private javax.swing.JPanel saveattendance;
    private javax.swing.JPanel settingsButton;
    // End of variables declaration//GEN-END:variables
}
