package vehler;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class Banpassenger extends javax.swing.JFrame {

    /**
     * Creates new form AdminHome
     */
    private String username;
    public Banpassenger()
    {
        
    }
    public Banpassenger(String username) {
        this.username=username;
        initComponents();
         Admin a=new Admin();
        a.gettabdata("call getp(?)", admintab);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        addVehicleButton = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        removeVehicleButton = new javax.swing.JPanel();
        addVehicleButton5 = new javax.swing.JPanel();
        Adddriver = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        settingsButton = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        logOutButton = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        banDriverButton2 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        banDriverButton3 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        banDriverButton4 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        addVehicleButton1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Adddriver1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Adddriver2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        admintab = new javax.swing.JTable();
        saveattendance = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 0, 102));
        jLabel11.setText("Make it happen.");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 670, -1, 50));

        jPanel3.setBackground(new java.awt.Color(51, 0, 102));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Vehler");

        addVehicleButton.setBackground(new java.awt.Color(51, 0, 102));
        addVehicleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addVehicleButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addVehicleButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addVehicleButtonMouseExited(evt);
            }
        });
        addVehicleButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Add Bus");
        addVehicleButton.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Transportation_25px.png"))); // NOI18N
        addVehicleButton.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 57, 30));

        removeVehicleButton.setBackground(new java.awt.Color(51, 0, 102));
        removeVehicleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                removeVehicleButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                removeVehicleButtonMouseExited(evt);
            }
        });
        removeVehicleButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addVehicleButton5.setBackground(new java.awt.Color(51, 0, 102));
        addVehicleButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addVehicleButton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addVehicleButton5MouseExited(evt);
            }
        });
        addVehicleButton5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        removeVehicleButton.add(addVehicleButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Adddriver.setBackground(new java.awt.Color(51, 0, 102));
        Adddriver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdddriverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AdddriverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AdddriverMouseExited(evt);
            }
        });
        Adddriver.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(240, 240, 240));
        jLabel12.setText("Add Driver");
        Adddriver.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 80, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Denied_25px.png"))); // NOI18N
        Adddriver.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 57, 30));

        settingsButton.setBackground(new java.awt.Color(51, 0, 102));
        settingsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settingsButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                settingsButtonMouseExited(evt);
            }
        });
        settingsButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(240, 240, 240));
        jLabel18.setText("More");
        settingsButton.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Settings_25px.png"))); // NOI18N
        settingsButton.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 57, 30));

        logOutButton.setBackground(new java.awt.Color(51, 0, 102));
        logOutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logOutButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logOutButtonMouseExited(evt);
            }
        });
        logOutButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(240, 240, 240));
        jLabel20.setText("Log Out");
        logOutButton.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Logout_Rounded_Up_25px.png"))); // NOI18N
        logOutButton.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 57, 30));

        banDriverButton2.setBackground(new java.awt.Color(51, 0, 102));
        banDriverButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                banDriverButton2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                banDriverButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                banDriverButton2MouseExited(evt);
            }
        });
        banDriverButton2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(240, 240, 240));
        jLabel26.setText("Ban Driver");
        banDriverButton2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Denied_25px.png"))); // NOI18N
        banDriverButton2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 57, 30));

        banDriverButton3.setBackground(new java.awt.Color(51, 0, 102));
        banDriverButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                banDriverButton3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                banDriverButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                banDriverButton3MouseExited(evt);
            }
        });
        banDriverButton3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(240, 240, 240));
        jLabel28.setText("Ban Bus");
        banDriverButton3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Denied_25px.png"))); // NOI18N
        banDriverButton3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 57, 30));

        banDriverButton4.setBackground(new java.awt.Color(51, 0, 102));
        banDriverButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                banDriverButton4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                banDriverButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                banDriverButton4MouseExited(evt);
            }
        });
        banDriverButton4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(240, 240, 240));
        jLabel30.setText("Ban Passenger");
        banDriverButton4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Denied_25px.png"))); // NOI18N
        banDriverButton4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 57, 30));

        addVehicleButton1.setBackground(new java.awt.Color(51, 0, 102));
        addVehicleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addVehicleButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addVehicleButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addVehicleButton1MouseExited(evt);
            }
        });
        addVehicleButton1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Home");
        addVehicleButton1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        Adddriver1.setBackground(new java.awt.Color(51, 0, 102));
        Adddriver1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Adddriver1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Adddriver1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Adddriver1MouseExited(evt);
            }
        });
        Adddriver1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(240, 240, 240));
        jLabel15.setText("Add Route");
        Adddriver1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 80, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Denied_25px.png"))); // NOI18N
        Adddriver1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 57, 30));

        Adddriver2.setBackground(new java.awt.Color(51, 0, 102));
        Adddriver2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Adddriver2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Adddriver2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Adddriver2MouseExited(evt);
            }
        });
        Adddriver2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(240, 240, 240));
        jLabel17.setText("Add Time");
        Adddriver2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 80, 30));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Denied_25px.png"))); // NOI18N
        Adddriver2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 57, 30));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addVehicleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(removeVehicleButton, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE))
                    .addComponent(settingsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logOutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Adddriver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(banDriverButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(banDriverButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(banDriverButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addVehicleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Adddriver1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Adddriver2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(addVehicleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(addVehicleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Adddriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Adddriver1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Adddriver2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(banDriverButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(banDriverButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(banDriverButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(settingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(logOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(removeVehicleButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 790));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 0, 102));
        jLabel14.setText("A wide range of controls in your hands.");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 640, -1, 50));

        admintab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Session", "BusNo", "From", "To", "Time", "Driver Name", "Driver ID", "Attendance"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        admintab.setRowHeight(28);
        admintab.setSelectionBackground(new java.awt.Color(51, 0, 102));
        admintab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                admintabMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(admintab);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 740, 320));

        saveattendance.setBackground(new java.awt.Color(153, 51, 255));
        saveattendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveattendanceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saveattendanceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saveattendanceMouseExited(evt);
            }
        });
        saveattendance.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 204, 204));
        jLabel23.setText("EMAIL");
        saveattendance.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));

        jLabel24.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(204, 204, 204));
        jLabel24.setText("Ban");
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });
        saveattendance.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jPanel2.add(saveattendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 500, 110, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1452, 779));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addVehicleButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addVehicleButtonMouseEntered
        // TODO add your handling code here:
        addVehicleButton.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_addVehicleButtonMouseEntered

    private void addVehicleButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addVehicleButtonMouseExited
        // TODO add your handling code here:
        addVehicleButton.setBackground(new Color(51,0,102));
    }//GEN-LAST:event_addVehicleButtonMouseExited

    private void AdddriverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdddriverMouseEntered
        // TODO add your handling code here:
        Adddriver.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_AdddriverMouseEntered

    private void AdddriverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdddriverMouseExited
        // TODO add your handling code here:
         Adddriver.setBackground(new Color(51,0,102));
    }//GEN-LAST:event_AdddriverMouseExited

    private void settingsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsButtonMouseEntered
        // TODO add your handling code here:
        settingsButton.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_settingsButtonMouseEntered

    private void settingsButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsButtonMouseExited
        // TODO add your handling code here:
         settingsButton.setBackground(new Color(51,0,102));
    }//GEN-LAST:event_settingsButtonMouseExited

    private void logOutButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutButtonMouseEntered
        // TODO add your handling code here:
        logOutButton.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_logOutButtonMouseEntered

    private void logOutButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutButtonMouseExited
        // TODO add your handling code here:
         logOutButton.setBackground(new Color(51,0,102));
    }//GEN-LAST:event_logOutButtonMouseExited

    private void removeVehicleButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeVehicleButtonMouseExited
        // TODO add your handling code here:
        removeVehicleButton.setBackground(new Color(51,0,102));
    }//GEN-LAST:event_removeVehicleButtonMouseExited

    private void removeVehicleButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeVehicleButtonMouseEntered
        // TODO add your handling code here:
        removeVehicleButton.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_removeVehicleButtonMouseEntered

    private void addVehicleButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addVehicleButton5MouseExited
        // TODO add your handling code here:
         addVehicleButton5.setBackground(new Color(51,0,102));
    }//GEN-LAST:event_addVehicleButton5MouseExited

    private void addVehicleButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addVehicleButton5MouseEntered
        // TODO add your handling code here:
         addVehicleButton5.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_addVehicleButton5MouseEntered

    private void addVehicleButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addVehicleButtonMouseClicked
        // TODO add your handling code here:
        AddVehicle av=new AddVehicle(username);
        this.setVisible(false);
        av.setVisible(true);
    }//GEN-LAST:event_addVehicleButtonMouseClicked

    private void AdddriverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdddriverMouseClicked
        // TODO add your handling code here:
    Admin a=new Admin();
    boolean chk=a.checkbusavail();
    if(chk){
        this.setVisible(false);
        RegistrationFormd reg=new RegistrationFormd();
        reg.setVisible(true);
    }
    else
    {
        JOptionPane.showMessageDialog(null, "Cannot Add Driver When NO Bus Is Available");
    }
    }//GEN-LAST:event_AdddriverMouseClicked

    private void settingsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsButtonMouseClicked
        // TODO add your handling code here:
      More as=new More(username);
        this.setVisible(false);
        as.setVisible(true);
    }//GEN-LAST:event_settingsButtonMouseClicked

    private void logOutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutButtonMouseClicked
        // TODO add your handling code here:
        LoginMain lm=new LoginMain();
        this.setVisible(false);
        lm.setVisible(true);
    }//GEN-LAST:event_logOutButtonMouseClicked

    private void admintabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admintabMouseClicked
        // TODO add your handling code here:
     

    }//GEN-LAST:event_admintabMouseClicked

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel24MouseClicked

    private void saveattendanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveattendanceMouseClicked
        // TODO add your handling code here:
                Admin a=new Admin();
        int id;
        try{
            DefaultTableModel model=(DefaultTableModel) admintab.getModel();
            String e=model.getValueAt(admintab.getSelectedRow(), 0).toString();
          //  id=Integer.parseInt(e);
             a.banb("call banp(?)", e);
            JOptionPane.showMessageDialog(null, "Passenger Banned Successfully");
        a.gettabdata("call getp(?)", admintab);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Some Error Occured While Banning");
        }
    }//GEN-LAST:event_saveattendanceMouseClicked

    private void saveattendanceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveattendanceMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_saveattendanceMouseEntered

    private void saveattendanceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveattendanceMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_saveattendanceMouseExited

    private void banDriverButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_banDriverButton2MouseClicked
        // TODO add your handling code here:
      BanDriver bd=new BanDriver(username);
        this.hide();
        bd.show();
        
        
    }//GEN-LAST:event_banDriverButton2MouseClicked

    private void banDriverButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_banDriverButton2MouseEntered
        // TODO add your handling code here:
         banDriverButton2.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_banDriverButton2MouseEntered

    private void banDriverButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_banDriverButton2MouseExited
        // TODO add your handling code here:
                 banDriverButton2.setBackground(new Color(51,0,102));

    }//GEN-LAST:event_banDriverButton2MouseExited

    private void banDriverButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_banDriverButton3MouseClicked
        // TODO add your handling code here:
          Banbus bd=new Banbus(username);
        this.hide();
        bd.show();
         
    }//GEN-LAST:event_banDriverButton3MouseClicked

    private void banDriverButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_banDriverButton3MouseEntered
        // TODO add your handling code here:
        banDriverButton3.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_banDriverButton3MouseEntered

    private void banDriverButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_banDriverButton3MouseExited
        // TODO add your handling code here:
                 banDriverButton3.setBackground(new Color(51,0,102));

    }//GEN-LAST:event_banDriverButton3MouseExited

    private void banDriverButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_banDriverButton4MouseClicked
        // TODO add your handling code here:
      
    }//GEN-LAST:event_banDriverButton4MouseClicked

    private void banDriverButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_banDriverButton4MouseEntered
        // TODO add your handling code here:
         banDriverButton4.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_banDriverButton4MouseEntered

    private void banDriverButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_banDriverButton4MouseExited
        // TODO add your handling code here:
                 banDriverButton4.setBackground(new Color(51,0,102));

    }//GEN-LAST:event_banDriverButton4MouseExited

    private void addVehicleButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addVehicleButton1MouseClicked
        // TODO add your handling code here:
         AdminHome bd=new AdminHome(username);
        this.hide();
        bd.show();
    }//GEN-LAST:event_addVehicleButton1MouseClicked

    private void addVehicleButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addVehicleButton1MouseEntered
        // TODO add your handling code here:
         addVehicleButton1.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_addVehicleButton1MouseEntered

    private void addVehicleButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addVehicleButton1MouseExited
        // TODO add your handling code here:
        addVehicleButton1.setBackground(new Color(51,0,102));
    }//GEN-LAST:event_addVehicleButton1MouseExited

    private void Adddriver1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Adddriver1MouseClicked
        // TODO add your handling code here:
         Addroute av=new Addroute(username);
        this.setVisible(false);
        av.setVisible(true);
    }//GEN-LAST:event_Adddriver1MouseClicked

    private void Adddriver1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Adddriver1MouseEntered
        // TODO add your handling code here:
         Adddriver1.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_Adddriver1MouseEntered

    private void Adddriver1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Adddriver1MouseExited
        // TODO add your handling code here:
         Adddriver1.setBackground(new Color(51,0,102));
    }//GEN-LAST:event_Adddriver1MouseExited

    private void Adddriver2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Adddriver2MouseClicked
        // TODO add your handling code here:
        Addtime aa=new Addtime(username);
        this.hide();
        aa.show();
    }//GEN-LAST:event_Adddriver2MouseClicked

    private void Adddriver2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Adddriver2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Adddriver2MouseEntered

    private void Adddriver2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Adddriver2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Adddriver2MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Banpassenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Banpassenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Banpassenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Banpassenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Banpassenger().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Adddriver;
    private javax.swing.JPanel Adddriver1;
    private javax.swing.JPanel Adddriver2;
    private javax.swing.JPanel addVehicleButton;
    private javax.swing.JPanel addVehicleButton1;
    private javax.swing.JPanel addVehicleButton5;
    private javax.swing.JTable admintab;
    private javax.swing.JPanel banDriverButton2;
    private javax.swing.JPanel banDriverButton3;
    private javax.swing.JPanel banDriverButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel logOutButton;
    private javax.swing.JPanel removeVehicleButton;
    private javax.swing.JPanel saveattendance;
    private javax.swing.JPanel settingsButton;
    // End of variables declaration//GEN-END:variables
}
