/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vehler;

import java.awt.Color;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import oracle.jdbc.OracleTypes;

/**
 *
 * @author user
 */
public class BookRide1 extends javax.swing.JFrame {
public int idd;
    /**
     * Creates new form BookRide
     */
    public String[] arr = new String[]{ "0","0","0","0","0","0","0","0","0","0","0" }; /////database value for reserved seats
   
    public String newseats;
    public String seat;
    public String b="";
    private String username;
    private String pname;
    public BookRide1(String username,String name) {
        this.username=username;
        this.pname=name;
        
        initComponents();
       jLabel5.hide();
       donebtn.hide();
       seatshow();
      
//        getTimes();
//        getLocations();
    }
      public BookRide1(int id) {
       idd=id;
        
        initComponents();
       jLabel5.hide();
       jLabel25.hide();
       donebtn.hide();
          getseats();
       seatshow();
      
//        getTimes();
//        getLocations();
    }
    public BookRide1() {
//        initComponents();
    }
    public void getseats()
    {
    
       
  // String sql=query;
   try
  {
       Connection1 cc=new Connection1();
             Connection con=cc.setconnection();
      Statement s=con.createStatement();
    CallableStatement stmt = con.prepareCall("{call GETSEATS(?)}"); 
     stmt.registerOutParameter(1,OracleTypes.CURSOR);

            stmt.execute();
  ResultSet rs = (ResultSet) stmt.getObject(1);
    while(rs.next())
            {
               String a=(rs.getString("bus")); 
               String b=(rs.getString("seatno"));
               if(b.contains("1"))
               {
                arr[1-1]="1";
               }
               if(b.contains("2"))
               {
                arr[2-1]="1";
               }
               if(b.contains("3"))
               {
                arr[3-1]="1";
               }
               if(b.contains("4"))
               {
                arr[4-1]="1";
               }
               if(b.contains("5"))
               {
                arr[5-1]="1";
               }
               if(b.contains("6"))
               {
                arr[6-1]="1";
               }
               if(b.contains("7"))
               {
                arr[7-1]="1";
               }
               if(b.contains("8"))
               {
                arr[8-1]="1";
               }
               if(b.contains("9"))
               {
                arr[9-1]="1";
               }
               if(b.contains(" 10,"))
               {
                arr[10-1]="1";
               }
               if(b.contains(" 11,"))
               {
                arr[11-1]="1";
               }
               String c=(rs.getString("pid"));
               
                
               
             
                
           }
    System.out.println("Stored Procedure executed successfully");
  }
  catch(Exception err)
  {
    System.out.println("An error has occurred.");
    System.out.println("See full details below.");
    err.printStackTrace();
  } 
       
    }
    
    
    public void setlabels(String busnumber,String from,String too,String arrive,String depart,String seats)
    {
        buslabel.setText(busnumber);
        Fromlabel.setText(from);
        tolabel.setText(too);
        arrivelabel.setText(arrive);
        departlabel.setText(depart);
        seat=seats;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Confirmbtn = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Backbtn = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        buslabel = new javax.swing.JLabel();
        Fromlabel = new javax.swing.JLabel();
        tolabel = new javax.swing.JLabel();
        arrivelabel = new javax.swing.JLabel();
        departlabel = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        donebtn = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        bookRideButton = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        removeVehicleButton = new javax.swing.JPanel();
        addVehicleButton5 = new javax.swing.JPanel();
        myRidesButton = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        logOutButton = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        bookRideButton1 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        bookRideButton2 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Select Seats:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 50, -1, -1));

        Confirmbtn.setBackground(new java.awt.Color(153, 51, 255));
        Confirmbtn.setForeground(new java.awt.Color(255, 255, 255));
        Confirmbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConfirmbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ConfirmbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ConfirmbtnMouseExited(evt);
            }
        });
        Confirmbtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Confirm");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        Confirmbtn.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jPanel2.add(Confirmbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 190, 160, 40));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Arrival Time:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 140, 30));

        Backbtn.setBackground(new java.awt.Color(153, 51, 255));
        Backbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BackbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BackbtnMouseExited(evt);
            }
        });
        Backbtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("Back");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        Backbtn.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jPanel2.add(Backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 580, 140, 40));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Session:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 120, 30));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Bus Number:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 120, 30));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("From:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 120, 30));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("To:");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 120, 30));

        buslabel.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        buslabel.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(buslabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 120, 30));

        Fromlabel.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        Fromlabel.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(Fromlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 180, 30));

        tolabel.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tolabel.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(tolabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 180, 30));

        arrivelabel.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        arrivelabel.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(arrivelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 120, 30));

        departlabel.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        departlabel.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(departlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 140, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 306, 300, 30));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, 350, 20));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 330, 30));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, 260, 20));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("04-Jan-2020");
        jLabel25.setToolTipText("");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 450, 220, 20));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 490, 170, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ticket1.jpg"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 900, 320));

        donebtn.setBackground(new java.awt.Color(153, 51, 255));
        donebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                donebtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                donebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                donebtnMouseExited(evt);
            }
        });
        donebtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(204, 204, 204));
        jLabel27.setText("Done");
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });
        donebtn.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 40, -1));

        jPanel2.add(donebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 580, 160, 40));

        jCheckBox1.setBackground(new java.awt.Color(153, 153, 153));
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("1");
        jPanel2.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 30, -1, -1));

        jCheckBox2.setBackground(new java.awt.Color(153, 153, 153));
        jCheckBox2.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setText("2");
        jPanel2.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 50, -1, -1));

        jCheckBox3.setBackground(new java.awt.Color(153, 153, 153));
        jCheckBox3.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox3.setText("3");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 70, -1, -1));

        jCheckBox4.setBackground(new java.awt.Color(153, 153, 153));
        jCheckBox4.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox4.setText("4");
        jPanel2.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 30, -1, -1));

        jCheckBox5.setBackground(new java.awt.Color(153, 153, 153));
        jCheckBox5.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox5.setText("5");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 50, -1, -1));

        jCheckBox6.setBackground(new java.awt.Color(153, 153, 153));
        jCheckBox6.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox6.setText("6");
        jPanel2.add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 70, -1, -1));

        jCheckBox7.setBackground(new java.awt.Color(153, 153, 153));
        jCheckBox7.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox7.setText("7");
        jPanel2.add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 30, -1, -1));

        jCheckBox8.setBackground(new java.awt.Color(153, 153, 153));
        jCheckBox8.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox8.setText("8");
        jPanel2.add(jCheckBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 50, -1, -1));

        jCheckBox9.setBackground(new java.awt.Color(153, 153, 153));
        jCheckBox9.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox9.setText("9");
        jPanel2.add(jCheckBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 70, -1, -1));

        jCheckBox10.setBackground(new java.awt.Color(153, 153, 153));
        jCheckBox10.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox10.setText("10");
        jPanel2.add(jCheckBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 30, -1, -1));

        jPanel3.setBackground(new java.awt.Color(51, 0, 102));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Vehler");

        bookRideButton.setBackground(new java.awt.Color(51, 0, 102));
        bookRideButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookRideButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bookRideButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bookRideButtonMouseExited(evt);
            }
        });
        bookRideButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Home");
        bookRideButton.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Webp.net-resizeimage (1).png"))); // NOI18N
        bookRideButton.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 57, 30));

        removeVehicleButton.setBackground(new java.awt.Color(51, 0, 102));
        removeVehicleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                removeVehicleButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                removeVehicleButtonMouseExited(evt);
            }
        });
        removeVehicleButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addVehicleButton5.setBackground(new java.awt.Color(51, 0, 102));
        addVehicleButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addVehicleButton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addVehicleButton5MouseExited(evt);
            }
        });
        addVehicleButton5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        removeVehicleButton.add(addVehicleButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        myRidesButton.setBackground(new java.awt.Color(51, 0, 102));
        myRidesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myRidesButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                myRidesButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                myRidesButtonMouseExited(evt);
            }
        });
        myRidesButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(240, 240, 240));
        jLabel12.setText("My Rides");
        myRidesButton.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Present_25px_1.png"))); // NOI18N
        myRidesButton.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 57, 30));

        logOutButton.setBackground(new java.awt.Color(51, 0, 102));
        logOutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logOutButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logOutButtonMouseExited(evt);
            }
        });
        logOutButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(240, 240, 240));
        jLabel20.setText("Log Out");
        logOutButton.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Logout_Rounded_Up_25px.png"))); // NOI18N
        logOutButton.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 57, 30));

        bookRideButton1.setBackground(new java.awt.Color(51, 0, 102));
        bookRideButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookRideButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bookRideButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bookRideButton1MouseExited(evt);
            }
        });
        bookRideButton1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(240, 240, 240));
        jLabel28.setText("Book Ride");
        bookRideButton1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Add_Key_25px.png"))); // NOI18N
        bookRideButton1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 57, 30));

        bookRideButton2.setBackground(new java.awt.Color(51, 0, 102));
        bookRideButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookRideButton2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bookRideButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bookRideButton2MouseExited(evt);
            }
        });
        bookRideButton2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(240, 240, 240));
        jLabel29.setText("Schedule");
        bookRideButton2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Bus_25px.png"))); // NOI18N
        bookRideButton2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 57, 30));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(jLabel1))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 38, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bookRideButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(297, 297, 297)
                                .addComponent(removeVehicleButton, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                            .addComponent(logOutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(myRidesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bookRideButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bookRideButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(bookRideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(bookRideButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(bookRideButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(myRidesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addComponent(removeVehicleButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(logOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 350, 646));

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hamza\\Downloads\\download.jfif")); // NOI18N
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 0, 300, 180));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1350, 633));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void seatshow()
    {
        if(arr[0].equals("1"))
        {
            jCheckBox1.hide();
        } 
        if(arr[1].equals("1"))
        {
            jCheckBox2.hide();
        } 
        if(arr[2].equals("1"))
        {
            jCheckBox3.hide();
        } 
        if(arr[3].equals("1"))
        {
            jCheckBox4.hide();
        } 
        if(arr[4].equals("1"))
        {
            jCheckBox5.hide();
        } 
        if(arr[5].equals("1"))
        {
            jCheckBox6.hide();
        } 
        if(arr[6].equals("1"))
        {
            jCheckBox7.hide();
        } 
        if(arr[7].equals("1"))
        {
            jCheckBox8.hide();
        } 
        if(arr[8].equals("1"))
        {
            jCheckBox9.hide();
        } 
        if(arr[9].equals("1"))
        {
            jCheckBox10.hide();
        } 
    
    }
    
    
    
    
    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        Confirmbtn.action(null,null);
    }//GEN-LAST:event_jLabel14MouseClicked
//    public void getTimes()
//    {
//        
//       
//        ResultSet rst = null;
//        try
//        {
//        DbConnection conn = new DbConnection();
//        conn.OpenConnection();
//        String sql="Select ID,ArrivalTime,DepartTime,Time from Time";
//        rst= conn.GetData(sql);      
//          
//         while(rst.next()){
//            String ID=rst.getString("ID");
//            String arrtime=rst.getString("ArrivalTime");
//            String depttime=rst.getString("DepartTime");
//            String times=rst.getString("Time");
//            timeCombo.addItem(times);
//            
//                }
//         
//       
//        
//           conn.CloseConnection();
//          }
//        catch(Exception e){
//          JOptionPane.showMessageDialog(null, e+"Eroor in Getting Time");  
//        }
//        
//    }
//     public void getLocations()
//    {
//        
//       
//        ResultSet rst = null;
//        try
//        {
//        DbConnection conn = new DbConnection();
//        conn.OpenConnection();
//        String sql="Select From1,To1 from Locations";
//        rst= conn.GetData(sql);      
//          
//         while(rst.next()){
//            String from1=rst.getString("From1");
//            String to1=rst.getString("To1");
//            fromCombo.addItem(from1);
//            toCombo.addItem(to1);
//            
//                }
//       
//        
//           conn.CloseConnection();
//          }
//        catch(Exception e){
//          JOptionPane.showMessageDialog(null,"Error in Getting Locations");  
//        }
//        
//    }
//     public void show1(){
//            jLabel2.show();
//            jLabel3.show();
//            jLabel5.show();
//            fromCombo.show();
//            toCombo.show();
//            timeCombo.show();
//            Confirmbtn.show();
//     
//     
//     }
//
    public void updateseats(String busno,String From1,String To1,String Arrival,String depart,String seats)
    {
        
        int flag;
        ResultSet rst = null;
        try
        {
        DbConnection conn = new DbConnection();
        conn.OpenConnection();
        String sql="UPDATE Rides SET SeatsLeft = '"+ seats +"' where BusNumber = '"+busno+ "' and From1 = '"+From1+ "' and To1 = '"+To1+ "'";
        conn.InsertUpdateDelete(sql);
//           if(flag == 1){
//               JOptionPane.showMessageDialog(null, "YOUR PASSWORD HAS BEEN CHANGED  ");
//           }
//           else{
//                JOptionPane.showMessageDialog(null, "YOUR PASSWORD COULDn't BE CHANGED" );
//           }
        }
        catch(Exception e){
             JOptionPane.showMessageDialog(null, "UpdateSeats Query Failed");
        }
        
    }
//    
    public void execquries()
    {
         updateseats(buslabel.getText(), Fromlabel.getText(), tolabel.getText(), arrivelabel.getText(), departlabel.getText(), newseats);
    }
    public int chkseats()
    {
        int a=0;
        
        if(jCheckBox1.isSelected())
        {
            a+=1;
            b+="1, ";
        }
        if(jCheckBox2.isSelected())
        {
            a+=1;
            b+="2, ";
        }
        if(jCheckBox3.isSelected())
        {
            a+=1;
            b+="3, ";
        }
       if(jCheckBox4.isSelected())
        {
            a+=1;
            b+="4, ";
        }
       if(jCheckBox5.isSelected())
        {
            a+=1;
            b+="5, ";
        }
       if(jCheckBox6.isSelected())
        {
            a+=1;
            b+="6, ";
        }
       if(jCheckBox7.isSelected())
        {
            a+=1;
            b+="7, ";
        }
        if(jCheckBox8.isSelected())
        {
            a+=1;
            b+="8, ";
        }
       if(jCheckBox9.isSelected())
        {
            a+=1;
            b+="9, ";
        }
       if(jCheckBox10.isSelected())
        {
            a+=1;
            b+="10, ";
        }
   
       
        return a;
    }
    public void ticketdisplay()
    {
        PassengerHome p=new PassengerHome();
        
            Backbtn.hide();
            donebtn.show();
            jLabel5.show();
            jLabel25.show();
            jLabel19.setText(p.nome);
            jLabel22.setText(tolabel.getText());
            jLabel23.setText(arrivelabel.getText());
       //     jLabel24.setText(jTextField1.getText());
           // jLabel25.setText();
           jLabel24.setText(b);
            jLabel26.setText(seat);
             
         //   jTextField1.setText("");
    }
    private void ConfirmbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfirmbtnMouseClicked
        // TODO add your handling code here:
        JDialog.setDefaultLookAndFeelDecorated(true);
    int response = JOptionPane.showConfirmDialog(null, "Book seat?", "Confirmation",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
    if (response == JOptionPane.NO_OPTION) {
     
    } else if (response == JOptionPane.YES_OPTION) {
        
        if(!jCheckBox1.isSelected()&&!jCheckBox2.isSelected()&&!jCheckBox3.isSelected()&&!jCheckBox4.isSelected()&&!jCheckBox5.isSelected()&&!jCheckBox6.isSelected()&&
                !jCheckBox7.isSelected()&&!jCheckBox8.isSelected()&&!jCheckBox9.isSelected()&&!jCheckBox10.isSelected())
        {
             JOptionPane.showMessageDialog(null, "Please Select Seats");
        }
        else{
//            System.out.println(chkseats());
//                newseats=""+(Integer.parseInt(seat)-chkseats());
//        if(Integer.parseInt(newseats)<0)
//        {
//             JOptionPane.showMessageDialog(null, "Entered Quantity Is Greater than Available Seats");
//        }
//        else{
chkseats();
            Confirmbtn.hide();
            ticketdisplay();
//         //   execquries();
//       
//        }
          
       
        }
    } else if (response == JOptionPane.CLOSED_OPTION) {
      
    }
//        String currentLocation=String.valueOf(fromCombo.getSelectedItem());
//        String finalLocation=String.valueOf(toCombo.getSelectedItem());
//        String time=String.valueOf(timeCombo.getSelectedItem());
//        jLabel2.hide();
//        jLabel3.hide();
//        jLabel5.hide();
//        fromCombo.hide();
//        toCombo.hide();
//        timeCombo.hide();
//        Confirmbtn.hide();
//        jPanel1.show();
//        getRides(currentLocation, finalLocation);
//        //JOptionPane.showMessageDialog(null,"PLEASE WAIT, WE're FINDING A DRIVER FOR YOU ");
      
    }//GEN-LAST:event_ConfirmbtnMouseClicked

    private void ConfirmbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfirmbtnMouseEntered
        // TODO add your handling code here:
        Confirmbtn.setBackground(new Color(204,153,255));
    }//GEN-LAST:event_ConfirmbtnMouseEntered

    private void ConfirmbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfirmbtnMouseExited
        // TODO add your handling code here:
        Confirmbtn.setBackground(new Color(153,51,255));
    }//GEN-LAST:event_ConfirmbtnMouseExited

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15MouseClicked

    private void BackbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackbtnMouseClicked
        // TODO add your handling code here:
        this.hide();
        BookRide br=new BookRide(idd);
        br.show();
    }//GEN-LAST:event_BackbtnMouseClicked

    private void BackbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackbtnMouseEntered
        // TODO add your handling code here:
           Backbtn.setBackground(new Color(204,153,255));
    }//GEN-LAST:event_BackbtnMouseEntered

    private void BackbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackbtnMouseExited
        // TODO add your handling code here:
          Backbtn.setBackground(new Color(153,51,255));
    }//GEN-LAST:event_BackbtnMouseExited

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel27MouseClicked

    private void donebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_donebtnMouseClicked
        // TODO add your handling code here:
        //        BookRide br=new BookRide(username,pname);
        //        this.setVisible(false);
        //        br.setVisible(true);
        insertseat();
     this.hide();
     PassengerHome p=new PassengerHome(idd);
     p.show();
    }//GEN-LAST:event_donebtnMouseClicked

    public void insertseat()
    {
          try
  {

      Connection1 cc=new Connection1();
      Connection con=cc.setconnection();
      Statement s=con.createStatement();
      CallableStatement stmt = con.prepareCall("{call insertseats(?,?,?,?)}"); 
     //stmt.registerOutParameter(1,OracleTypes.CURSOR);
      stmt.setString(1, Fromlabel.getText());
      stmt.setString(2, jLabel24.getText());
      stmt.setInt(3, idd);
         stmt.setInt(4, chkseats());
      stmt.execute();
            JOptionPane.showMessageDialog(null, "Seats Booked");

  }
  catch(Exception err)
  {
    System.out.println("An error has occurred.");
    System.out.println("See full details below.");
    err.printStackTrace();
  
 
              JOptionPane.showMessageDialog(null, err);
              
  }  
   
        
        
        
    }
    private void donebtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_donebtnMouseEntered
        // TODO add your handling code here:
        donebtn.setBackground(new Color(204,153,255));
    }//GEN-LAST:event_donebtnMouseEntered

    private void donebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_donebtnMouseExited
        // TODO add your handling code here:
        donebtn.setBackground(new Color(153,51,255));
    }//GEN-LAST:event_donebtnMouseExited

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void bookRideButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookRideButtonMouseClicked
        // TODO add your handling code here:
  this.hide();
     PassengerHome p=new PassengerHome(idd);
     p.show();
    }//GEN-LAST:event_bookRideButtonMouseClicked

    private void bookRideButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookRideButtonMouseEntered
        // TODO add your handling code here:
        bookRideButton.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_bookRideButtonMouseEntered

    private void bookRideButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookRideButtonMouseExited
        // TODO add your handling code here:
        bookRideButton.setBackground(new Color(51,0,102));
    }//GEN-LAST:event_bookRideButtonMouseExited

    private void addVehicleButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addVehicleButton5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_addVehicleButton5MouseEntered

    private void addVehicleButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addVehicleButton5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_addVehicleButton5MouseExited

    private void removeVehicleButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeVehicleButtonMouseEntered
        // TODO add your handling code here:
        removeVehicleButton.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_removeVehicleButtonMouseEntered

    private void removeVehicleButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeVehicleButtonMouseExited
        // TODO add your handling code here:
        removeVehicleButton.setBackground(new Color(51,0,102));
    }//GEN-LAST:event_removeVehicleButtonMouseExited

    private void myRidesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myRidesButtonMouseClicked
        // TODO add your handling code here:
        MyRides mr=new MyRides(idd);
        this.setVisible(false);
        mr.setVisible(true);
    }//GEN-LAST:event_myRidesButtonMouseClicked

    private void myRidesButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myRidesButtonMouseEntered
        // TODO add your handling code here:
        myRidesButton.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_myRidesButtonMouseEntered

    private void myRidesButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myRidesButtonMouseExited
        // TODO add your handling code here:
        myRidesButton.setBackground(new Color(51,0,102));
    }//GEN-LAST:event_myRidesButtonMouseExited

    private void logOutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutButtonMouseClicked
        // TODO add your handling code here:
        LoginMain lm=new LoginMain();
        this.setVisible(false);
        lm.setVisible(true);
    }//GEN-LAST:event_logOutButtonMouseClicked

    private void logOutButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutButtonMouseEntered
        // TODO add your handling code here:
        logOutButton.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_logOutButtonMouseEntered

    private void logOutButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutButtonMouseExited
        // TODO add your handling code here:
        logOutButton.setBackground(new Color(51,0,102));
    }//GEN-LAST:event_logOutButtonMouseExited

    private void bookRideButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookRideButton1MouseClicked
        // TODO add your handling code here:
        BookRide br=new BookRide(idd);
        this.setVisible(false);
        br.setVisible(true);
    }//GEN-LAST:event_bookRideButton1MouseClicked

    private void bookRideButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookRideButton1MouseEntered
        // TODO add your handling code here:
        bookRideButton1.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_bookRideButton1MouseEntered

    private void bookRideButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookRideButton1MouseExited
        // TODO add your handling code here:
        bookRideButton1.setBackground(new Color(51,0,102));
    }//GEN-LAST:event_bookRideButton1MouseExited

    private void bookRideButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookRideButton2MouseClicked
        // TODO add your handling code here:
        Schedule s= new Schedule(idd);
        this.setVisible(false);
        s.setVisible(true);
    }//GEN-LAST:event_bookRideButton2MouseClicked

    private void bookRideButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookRideButton2MouseEntered
        // TODO add your handling code here:
        bookRideButton2.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_bookRideButton2MouseEntered

    private void bookRideButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookRideButton2MouseExited
        // TODO add your handling code here:
        bookRideButton2.setBackground(new Color(51,0,102));
    }//GEN-LAST:event_bookRideButton2MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookRide1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookRide1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookRide1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookRide1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookRide1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Backbtn;
    private javax.swing.JPanel Confirmbtn;
    private javax.swing.JLabel Fromlabel;
    private javax.swing.JPanel addVehicleButton5;
    private javax.swing.JLabel arrivelabel;
    private javax.swing.JPanel bookRideButton;
    private javax.swing.JPanel bookRideButton1;
    private javax.swing.JPanel bookRideButton2;
    private javax.swing.JLabel buslabel;
    private javax.swing.JLabel departlabel;
    private javax.swing.JPanel donebtn;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel logOutButton;
    private javax.swing.JPanel myRidesButton;
    private javax.swing.JPanel removeVehicleButton;
    private javax.swing.JLabel tolabel;
    // End of variables declaration//GEN-END:variables
}
