/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vehler;

import java.awt.Color;
import java.sql.CallableStatement;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;
import oracle.jdbc.OracleTypes;
/**
 *
 * @author user
 */
public class Currentrideact extends javax.swing.JFrame {

    /**
     * Creates new form DriverHome
     */
    public int idd;
    private String pname,username;
    private String name1,fName1,age1,user1,pass1,cnic1,contactNo1,dob1,sec1;
  public Currentrideact(int id) {
      idd=id;
     
//        DriverCar pp=new DriverCar();
//        pp.getRDriverName(username);
          initComponents();
           jLabel2.hide();
           jPanel1.hide();
           stopbtn.hide();
           Collect.hide();
 //       mm(pp.getName1());
//        registerName1.setText(pp.getName1());
//        registerFather1.setText(pp.getfName1());
//        registerAge1.setText(pp.getAge1());
//        cnicText.setText(pp.getCnic1());
//        contactnoText.setText(pp.getContactNo1());
//        email.setText(pp.getSec1());
//        this.dob.setText(pp.getDob1());
        
    }

     
    public Currentrideact(String id,String pname) {
        username=id;
        this.pname=pname;
//        DriverCar pp=new DriverCar();
//        pp.getRDriverName(username);
          initComponents();
 //       mm(pp.getName1());
//        registerName1.setText(pp.getName1());
//        registerFather1.setText(pp.getfName1());
//        registerAge1.setText(pp.getAge1());
//        cnicText.setText(pp.getCnic1());
//        contactnoText.setText(pp.getContactNo1());
//        email.setText(pp.getSec1());
//        this.dob.setText(pp.getDob1());
        
    }
     public Currentrideact(String id,String pname,String fname,String age,String cnic,String contact,String dob,String sec) {
        username=id;
        this.pname=pname;
//        name1=pname;
//        fName1=fname;
//        age1=age;
//        cnic1=cnic;
//        contactNo1=contact;
//        dob1=dob;
//        sec1=sec;
        initComponents();
//        mm(pname);
//        registerName1.setText(pname);
//        registerFather1.setText(fName1);
//        registerAge1.setText(age1);
//        cnicText.setText(cnic1);
//        contactnoText.setText(contactNo1);
//        this.dob.setText(dob1);
//        email.setText(sec1);
////        
    }
    public Currentrideact()
    {
        
    }
    
    public void mm(String namee)
    {
//        changepassbtn.hide();
//        Save2.hide();
//        jLabel48.hide();
//        jLabel53.hide();
//        jLabel54.hide();
//        jLabel22.hide();
//        dob2.hide();
//        dob3.hide();
//        dob4.hide();
//        dob5.hide();
//        welcome.setText(namee);
//       
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        bookRideButton = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        removeVehicleButton = new javax.swing.JPanel();
        addVehicleButton5 = new javax.swing.JPanel();
        myRidesButton = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        logOutButton = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        bookRideButton1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        bookRideButton2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        stopbtn = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        startbtn = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        Collect = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 0, 102));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Vehler");

        bookRideButton.setBackground(new java.awt.Color(51, 0, 102));
        bookRideButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookRideButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bookRideButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bookRideButtonMouseExited(evt);
            }
        });
        bookRideButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Home");
        bookRideButton.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Webp.net-resizeimage (1).png"))); // NOI18N
        bookRideButton.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 57, 30));

        removeVehicleButton.setBackground(new java.awt.Color(51, 0, 102));
        removeVehicleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                removeVehicleButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                removeVehicleButtonMouseExited(evt);
            }
        });
        removeVehicleButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addVehicleButton5.setBackground(new java.awt.Color(51, 0, 102));
        addVehicleButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addVehicleButton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addVehicleButton5MouseExited(evt);
            }
        });
        addVehicleButton5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        removeVehicleButton.add(addVehicleButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        myRidesButton.setBackground(new java.awt.Color(51, 0, 102));
        myRidesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myRidesButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                myRidesButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                myRidesButtonMouseExited(evt);
            }
        });
        myRidesButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(240, 240, 240));
        jLabel12.setText("Prevous Rides");
        myRidesButton.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Present_25px_1.png"))); // NOI18N
        myRidesButton.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 57, 30));

        logOutButton.setBackground(new java.awt.Color(51, 0, 102));
        logOutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logOutButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logOutButtonMouseExited(evt);
            }
        });
        logOutButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(240, 240, 240));
        jLabel20.setText("Log Out");
        logOutButton.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Logout_Rounded_Up_25px.png"))); // NOI18N
        logOutButton.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 57, 30));

        bookRideButton1.setBackground(new java.awt.Color(51, 0, 102));
        bookRideButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookRideButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bookRideButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bookRideButton1MouseExited(evt);
            }
        });
        bookRideButton1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Current Ride Actions");
        bookRideButton1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Add_Key_25px.png"))); // NOI18N
        bookRideButton1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 57, 30));

        bookRideButton2.setBackground(new java.awt.Color(51, 0, 102));
        bookRideButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookRideButton2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bookRideButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bookRideButton2MouseExited(evt);
            }
        });
        bookRideButton2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("Today's Schedule");
        bookRideButton2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Bus_25px.png"))); // NOI18N
        bookRideButton2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 57, 30));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addComponent(removeVehicleButton, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(myRidesButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bookRideButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bookRideButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bookRideButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(logOutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(104, 104, 104))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(bookRideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(bookRideButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookRideButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(myRidesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124)
                .addComponent(removeVehicleButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(logOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 350, 670));

        stopbtn.setBackground(new java.awt.Color(255, 255, 255));
        stopbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 102, 255), 3));
        stopbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stopbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                stopbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                stopbtnMouseExited(evt);
            }
        });

        jLabel46.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(102, 102, 102));
        jLabel46.setText("Stop");
        jLabel46.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel46MouseExited(evt);
            }
        });

        javax.swing.GroupLayout stopbtnLayout = new javax.swing.GroupLayout(stopbtn);
        stopbtn.setLayout(stopbtnLayout);
        stopbtnLayout.setHorizontalGroup(
            stopbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stopbtnLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel46)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        stopbtnLayout.setVerticalGroup(
            stopbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stopbtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel46)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(stopbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 150, 50));

        startbtn.setBackground(new java.awt.Color(255, 255, 255));
        startbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 102, 255), 3));
        startbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                startbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                startbtnMouseExited(evt);
            }
        });

        jLabel48.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(102, 102, 102));
        jLabel48.setText("Start");
        jLabel48.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel48MouseExited(evt);
            }
        });

        javax.swing.GroupLayout startbtnLayout = new javax.swing.GroupLayout(startbtn);
        startbtn.setLayout(startbtnLayout);
        startbtnLayout.setHorizontalGroup(
            startbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startbtnLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel48)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        startbtnLayout.setVerticalGroup(
            startbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startbtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel48)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(startbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 150, 50));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel2.setText("Ride Has Started");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 760, 270));

        Collect.setBackground(new java.awt.Color(255, 255, 255));
        Collect.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 102, 255), 3));
        Collect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CollectMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CollectMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CollectMouseExited(evt);
            }
        });

        jLabel49.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(102, 102, 102));
        jLabel49.setText("Collect");
        jLabel49.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel49MouseExited(evt);
            }
        });

        javax.swing.GroupLayout CollectLayout = new javax.swing.GroupLayout(Collect);
        Collect.setLayout(CollectLayout);
        CollectLayout.setHorizontalGroup(
            CollectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CollectLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel49)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        CollectLayout.setVerticalGroup(
            CollectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CollectLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel49)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(Collect, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 550, 150, 50));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 670));

        jLabel47.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(153, 153, 153));
        jLabel47.setText("DOB");
        jPanel2.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1350, 670));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bookRideButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookRideButtonMouseClicked
        // TODO add your handling code here:
 driverhomee d=new driverhomee(idd);
        this.hide();
        d.show();
    }//GEN-LAST:event_bookRideButtonMouseClicked

    private void bookRideButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookRideButtonMouseEntered
        // TODO add your handling code here:
        bookRideButton.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_bookRideButtonMouseEntered

    private void bookRideButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookRideButtonMouseExited
        // TODO add your handling code here:
        bookRideButton.setBackground(new Color(51,0,102));
    }//GEN-LAST:event_bookRideButtonMouseExited

    private void addVehicleButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addVehicleButton5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_addVehicleButton5MouseEntered

    private void addVehicleButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addVehicleButton5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_addVehicleButton5MouseExited

    private void removeVehicleButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeVehicleButtonMouseEntered
        // TODO add your handling code here:
        removeVehicleButton.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_removeVehicleButtonMouseEntered

    private void removeVehicleButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeVehicleButtonMouseExited
        // TODO add your handling code here:
        removeVehicleButton.setBackground(new Color(51,0,102));
    }//GEN-LAST:event_removeVehicleButtonMouseExited

    private void myRidesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myRidesButtonMouseClicked
        // TODO add your handling code here:
        MyRidesd mr=new MyRidesd(idd);
        this.setVisible(false);
        mr.setVisible(true);
    }//GEN-LAST:event_myRidesButtonMouseClicked

    private void myRidesButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myRidesButtonMouseEntered
        // TODO add your handling code here:
        myRidesButton.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_myRidesButtonMouseEntered

    private void myRidesButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myRidesButtonMouseExited
        // TODO add your handling code here:
        myRidesButton.setBackground(new Color(51,0,102));
    }//GEN-LAST:event_myRidesButtonMouseExited

    private void logOutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutButtonMouseClicked
        // TODO add your handling code here:
        LoginMain lm=new LoginMain();
        this.setVisible(false);
        lm.setVisible(true);
    }//GEN-LAST:event_logOutButtonMouseClicked

    private void logOutButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutButtonMouseEntered
        // TODO add your handling code here:
        logOutButton.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_logOutButtonMouseEntered

    private void logOutButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutButtonMouseExited
        // TODO add your handling code here:
        logOutButton.setBackground(new Color(51,0,102));
    }//GEN-LAST:event_logOutButtonMouseExited

    private void bookRideButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookRideButton1MouseClicked
        // TODO add your handling code here:
      
    }//GEN-LAST:event_bookRideButton1MouseClicked

    private void bookRideButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookRideButton1MouseEntered
        // TODO add your handling code here:
        bookRideButton1.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_bookRideButton1MouseEntered

    private void bookRideButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookRideButton1MouseExited
        // TODO add your handling code here:
        bookRideButton1.setBackground(new Color(51,0,102));
    }//GEN-LAST:event_bookRideButton1MouseExited

    private void bookRideButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookRideButton2MouseClicked
        // TODO add your handling code here:
        Scheduled s= new Scheduled(idd);
        this.setVisible(false);
        s.setVisible(true);
    }//GEN-LAST:event_bookRideButton2MouseClicked

    private void bookRideButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookRideButton2MouseEntered
        // TODO add your handling code here:
        bookRideButton2.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_bookRideButton2MouseEntered

    private void bookRideButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookRideButton2MouseExited
        // TODO add your handling code here:
        bookRideButton2.setBackground(new Color(51,0,102));
    }//GEN-LAST:event_bookRideButton2MouseExited

    private void jLabel46MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel46MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel46MouseExited

    public void getschd(String query,int id,JTable table)
   {
    try
  {
 
      Connection1 cc=new Connection1();
      Connection con=cc.setconnection();
      Statement s=con.createStatement();
      CallableStatement stmt = con.prepareCall(query); 
     //stmt.registerOutParameter(1,OracleTypes.CURSOR);
      stmt.setInt(1, id);
      stmt.registerOutParameter(2,OracleTypes.CURSOR);
   
            stmt.execute();
      
  ResultSet rs = (ResultSet) stmt.getObject(2);
//  while (rs.next())
//  {
//      id=rs.getInt("did");
//  }
 
//  int id=rs.getInt("DID");
//  return id;
  table.setModel(DbUtils.resultSetToTableModel(rs));
//    System.out.println("Stored Procedure executed successfully");
  }
  catch(Exception err)
  {
    System.out.println("An error has occurred.");
    System.out.println("See full details below.");
    err.printStackTrace();
  
 
              JOptionPane.showMessageDialog(null, err);
             
  }  
    
   }
  
    private void stopbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stopbtnMouseClicked
        // TODO add your handling code here:
        jLabel2.setText("Ride has Stopped!!!");
        stopbtn.hide();
        jPanel1.show();
        Collect.show();
        getschd("{call ridedata(?,?)}", idd,jTable2);
//        int km=Integer.parseInt(String.valueOf(kmCombo.getSelectedItem()));
  //      Ride ride=new Ride();
    //    String billStatus="Unpaid";
      //  if(type=="Car")
//        {
        //    billCar=km*20;
          //  billText.setText(Integer.toString(billCar));
           // DateTime dt=new DateTime();
          //  String endtime=dt.getTime();
           // ride.updateEndTimeDateCar(username,endtime);
            //ride.updateBillStatusCar(username, billStatus,billCar);
        //}
        //        else if(type=="Rickshaw")
        //        {
            //            billRickshaw=km*15;
            //            billText.setText(Integer.toString(billRickshaw));
            //             DateTime dt=new DateTime();
            //            String endtime=dt.getTime();
            //            ride.updateEndTimeDateRickshaw(username,endtime);
            //            ride.updateBillStatusRickshaw(username, billStatus,billRickshaw);
            //        }
        //        else if(type=="Bus")
        //        {
            //            billBus=km*10;
            //            billText.setText(Integer.toString(billBus));
            //            DateTime dt=new DateTime();
            //            String endtime=dt.getTime();
            //            ride.updateEndTimeDateBus(username,endtime);
            //            ride.updateBillStatusBus(username, billStatus,billBus);
            //        }
    }//GEN-LAST:event_stopbtnMouseClicked

    private void stopbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stopbtnMouseEntered
        // TODO add your handling code here:
        stopbtn.setBackground(new Color(153,102,255));
        jLabel46.setForeground(new Color(255,255,255));

    }//GEN-LAST:event_stopbtnMouseEntered

    private void stopbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stopbtnMouseExited
        // TODO add your handling code here:
        stopbtn.setBackground(new Color(255,255,255));
        jLabel46.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_stopbtnMouseExited

    private void jLabel48MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel48MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel48MouseExited

    private void startbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startbtnMouseClicked
        // TODO add your handling code here:
        startbtn.hide();
        stopbtn.show();
        jLabel2.show();
    }//GEN-LAST:event_startbtnMouseClicked

    private void startbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startbtnMouseEntered
        // TODO add your handling code here:
        startbtn.setBackground(new Color(153,102,255));
    }//GEN-LAST:event_startbtnMouseEntered

    private void startbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startbtnMouseExited
        // TODO add your handling code here:
        startbtn.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_startbtnMouseExited

    private void jLabel49MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel49MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel49MouseExited
   public void deldt()
   {
           try
  {
 
      Connection1 cc=new Connection1();
      Connection con=cc.setconnection();
      Statement s=con.createStatement();
      CallableStatement stmt = con.prepareCall("{CALL delseat}"); 
     //stmt.registerOutParameter(1,OracleTypes.CURSOR);
     
    
      
            // run SP
            stmt.execute();
           
//  ResultSet rs = (ResultSet) stmt.getObject(1);
//   table.setModel(DbUtils.resultSetToTableModel(rs));
//    System.out.println("Stored Procedure executed successfully");
  }
  catch(Exception err)
  {
    System.out.println("An error has occurred.");
    System.out.println("See full details below.");
    err.printStackTrace();
  
 
              JOptionPane.showMessageDialog(null, err);
              
   }
   }

    public void insertpassdata(int pid,String seatno,String froml,String tol, String art, int fare)
    {
            try
  {
 
      
      Connection1 cc=new Connection1();
      Connection con=cc.setconnection();
      Statement s=con.createStatement();
      CallableStatement stmt = con.prepareCall("{call addrecords(?,?,?,?,?,?)}"); 
     //stmt.registerOutParameter(1,OracleTypes.CURSOR);
      stmt.setInt(1, pid);
      stmt.setString(2,seatno);
      stmt.setString(3, froml);
      stmt.setString(4, tol);
      stmt.setString(5, art);
      stmt.setInt(6, fare);
      
     // stmt.setInt(2, did);
       
    
      
            // run SP
            stmt.execute();
          
//  ResultSet rs = (ResultSet) stmt.getObject(1);
//   table.setModel(DbUtils.resultSetToTableModel(rs));
//    System.out.println("Stored Procedure executed successfully");
  }
  catch(Exception err)
  {
    System.out.println("An error has occurred.");
    System.out.println("See full details below.");
    err.printStackTrace();
  
 
              JOptionPane.showMessageDialog(null, err);
             
   }
   
   
    }
    
    private void CollectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CollectMouseClicked
        // TODO add your handling code here:
        
        for (int i=0;i<jTable2.getRowCount();i++)
        {
            String a=jTable2.getValueAt(i, 0).toString();
             String b=jTable2.getValueAt(i, 5).toString();
             int aa=Integer.parseInt(a);
             int bb=Integer.parseInt(b);
            insertpassdata(aa,jTable2.getValueAt(i, 1).toString(),jTable2.getValueAt(i, 2).toString(),jTable2.getValueAt(i, 3).toString(),jTable2.getValueAt(i, 4).toString(),bb);
        }
         JOptionPane.showMessageDialog(null, "Collected");
        deldt();
        
        
        
        
        
        
        
    }//GEN-LAST:event_CollectMouseClicked

    private void CollectMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CollectMouseEntered
        // TODO add your handling code here:
        Collect.setBackground(new Color(153,102,255));
    }//GEN-LAST:event_CollectMouseEntered

    private void CollectMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CollectMouseExited
        // TODO add your handling code here:
         Collect.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_CollectMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Currentrideact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Currentrideact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Currentrideact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Currentrideact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Currentrideact().setVisible(true);
               
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Collect;
    private javax.swing.JPanel addVehicleButton5;
    private javax.swing.JPanel bookRideButton;
    private javax.swing.JPanel bookRideButton1;
    private javax.swing.JPanel bookRideButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable2;
    private javax.swing.JPanel logOutButton;
    private javax.swing.JPanel myRidesButton;
    private javax.swing.JPanel removeVehicleButton;
    private javax.swing.JPanel startbtn;
    private javax.swing.JPanel stopbtn;
    // End of variables declaration//GEN-END:variables
}
