/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vehler;

import java.awt.Color;
import java.sql.CallableStatement;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import oracle.jdbc.OracleTypes;
/**
 *
 * @author user
 */
public class driverhomee extends javax.swing.JFrame {

    /**
     * Creates new form DriverHome
     */
    private int idd;
    private String pname,username;
    private String name1,fName1,age1,user1,pass1,cnic1,contactNo1,dob1,sec1;


     
    public driverhomee(String id,String pname) {
        username=id;
        this.pname=pname;
        DriverCar pp=new DriverCar();
        pp.getRDriverName(username);
          initComponents();
        mm(pp.getName1());
        registerName1.setText(pp.getName1());
        registerFather1.setText(pp.getfName1());
        registerAge1.setText(pp.getAge1());
        cnicText.setText(pp.getCnic1());
        contactnoText.setText(pp.getContactNo1());
      //  email.setText(pp.getSec1());
      //  this.dob.setText(pp.getDob1());
        
    }
       public driverhomee(int id) {
          initComponents();
          idd=id;
          getddata("{call getddata(?,?)}",id);
             changepassbtn.hide();
      
        
    }
     public void getddata(String query,int id)
     {
          try
  {
 
      Connection1 cc=new Connection1();
      Connection con=cc.setconnectionD();
      Statement s=con.createStatement();
      CallableStatement stmt = con.prepareCall(query); 
     //stmt.registerOutParameter(1,OracleTypes.CURSOR);
      stmt.setInt(1, id);
   
      stmt.registerOutParameter(2,OracleTypes.CURSOR);
   
            stmt.execute();
      
  ResultSet rs = (ResultSet) stmt.getObject(2);
  while (rs.next())
  {
      welcome.setText(rs.getString("dname"));
      registerName1.setText(rs.getString("dname"));
      registerFather1.setText(rs.getString("fname"));
      registerAge1.setText(rs.getString("age"));
      cnicText.setText(rs.getString("cnic"));
      contactnoText.setText(rs.getString("contact_no"));
  //    dob.setText((String)rs.getString("DOB"));
      //email.setText(rs.getString("email"));
      
      
  }
  
//  int id=rs.getInt("DID");
//  return id;
//   table.setModel(DbUtils.resultSetToTableModel(rs));
//    System.out.println("Stored Procedure executed successfully");
  }
  catch(Exception err)
  {
    System.out.println("An error has occurred.");
    System.out.println("See full details below.");
    err.printStackTrace();
  
 
              JOptionPane.showMessageDialog(null, err);
             
  }  
    
     }
     public driverhomee(String id,String pname,String fname,String age,String cnic,String contact,String dob,String sec) {
        username=id;
        this.pname=pname;
        name1=pname;
        fName1=fname;
        age1=age;
        cnic1=cnic;
        contactNo1=contact;
        dob1=dob;
        sec1=sec;
        initComponents();
        mm(pname);
        registerName1.setText(pname);
        registerFather1.setText(fName1);
        registerAge1.setText(age1);
        cnicText.setText(cnic1);
        contactnoText.setText(contactNo1);
       // this.dob.setText(dob1);
     //   email.setText(sec1);
//        
    }
    public driverhomee()
    {
        
    }
    
    public void mm(String namee)
    {
        changepassbtn.hide();
     
        welcome.setText(namee);
       
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        bookRideButton = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        removeVehicleButton = new javax.swing.JPanel();
        addVehicleButton5 = new javax.swing.JPanel();
        myRidesButton = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        logOutButton = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        bookRideButton1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        bookRideButton2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        bookRideButton3 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        removeVehicleButton1 = new javax.swing.JPanel();
        addVehicleButton6 = new javax.swing.JPanel();
        myRidesButton1 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        logOutButton1 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        bookRideButton4 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        bookRideButton5 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel38 = new javax.swing.JLabel();
        welcome = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        registerFather1 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        registerAge1 = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        registerName1 = new javax.swing.JTextField();
        cnicText = new javax.swing.JTextField();
        contactnoText = new javax.swing.JTextField();
        changepassbtn = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        changepassbtn1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        updatebtn = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 0, 102));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Vehler");

        bookRideButton.setBackground(new java.awt.Color(51, 0, 102));
        bookRideButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookRideButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bookRideButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bookRideButtonMouseExited(evt);
            }
        });
        bookRideButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Home");
        bookRideButton.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Webp.net-resizeimage (1).png"))); // NOI18N
        bookRideButton.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 57, 30));

        removeVehicleButton.setBackground(new java.awt.Color(51, 0, 102));
        removeVehicleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                removeVehicleButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                removeVehicleButtonMouseExited(evt);
            }
        });
        removeVehicleButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addVehicleButton5.setBackground(new java.awt.Color(51, 0, 102));
        addVehicleButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addVehicleButton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addVehicleButton5MouseExited(evt);
            }
        });
        addVehicleButton5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        removeVehicleButton.add(addVehicleButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        myRidesButton.setBackground(new java.awt.Color(51, 0, 102));
        myRidesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myRidesButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                myRidesButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                myRidesButtonMouseExited(evt);
            }
        });
        myRidesButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(240, 240, 240));
        jLabel12.setText("Prevous Rides");
        myRidesButton.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Present_25px_1.png"))); // NOI18N
        myRidesButton.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 57, 30));

        logOutButton.setBackground(new java.awt.Color(51, 0, 102));
        logOutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logOutButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logOutButtonMouseExited(evt);
            }
        });
        logOutButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(240, 240, 240));
        jLabel20.setText("Log Out");
        logOutButton.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Logout_Rounded_Up_25px.png"))); // NOI18N
        logOutButton.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 57, 30));

        bookRideButton1.setBackground(new java.awt.Color(51, 0, 102));
        bookRideButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookRideButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bookRideButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bookRideButton1MouseExited(evt);
            }
        });
        bookRideButton1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Current Ride Actions");
        bookRideButton1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Add_Key_25px.png"))); // NOI18N
        bookRideButton1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 57, 30));

        bookRideButton2.setBackground(new java.awt.Color(51, 0, 102));
        bookRideButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookRideButton2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bookRideButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bookRideButton2MouseExited(evt);
            }
        });
        bookRideButton2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("Today's Schedule");
        bookRideButton2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Bus_25px.png"))); // NOI18N
        bookRideButton2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 57, 30));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addComponent(removeVehicleButton, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(myRidesButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bookRideButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bookRideButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bookRideButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(logOutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(104, 104, 104))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(bookRideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(bookRideButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookRideButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(myRidesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124)
                .addComponent(removeVehicleButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(logOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 350, 670));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(51, 0, 102));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Vehler");

        bookRideButton3.setBackground(new java.awt.Color(51, 0, 102));
        bookRideButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookRideButton3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bookRideButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bookRideButton3MouseExited(evt);
            }
        });
        bookRideButton3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(240, 240, 240));
        jLabel26.setText("Home");
        bookRideButton3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));
        bookRideButton3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 57, 30));

        removeVehicleButton1.setBackground(new java.awt.Color(51, 0, 102));
        removeVehicleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                removeVehicleButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                removeVehicleButton1MouseExited(evt);
            }
        });
        removeVehicleButton1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addVehicleButton6.setBackground(new java.awt.Color(51, 0, 102));
        addVehicleButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addVehicleButton6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addVehicleButton6MouseExited(evt);
            }
        });
        addVehicleButton6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        removeVehicleButton1.add(addVehicleButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        myRidesButton1.setBackground(new java.awt.Color(51, 0, 102));
        myRidesButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myRidesButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                myRidesButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                myRidesButton1MouseExited(evt);
            }
        });
        myRidesButton1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(240, 240, 240));
        jLabel28.setText("My Rides");
        myRidesButton1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Present_25px_1.png"))); // NOI18N
        myRidesButton1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 57, 30));

        logOutButton1.setBackground(new java.awt.Color(51, 0, 102));
        logOutButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logOutButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logOutButton1MouseExited(evt);
            }
        });
        logOutButton1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(240, 240, 240));
        jLabel30.setText("Log Out");
        logOutButton1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Logout_Rounded_Up_25px.png"))); // NOI18N
        logOutButton1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 57, 30));

        bookRideButton4.setBackground(new java.awt.Color(51, 0, 102));
        bookRideButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookRideButton4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bookRideButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bookRideButton4MouseExited(evt);
            }
        });
        bookRideButton4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(240, 240, 240));
        jLabel32.setText("Book Ride");
        bookRideButton4.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Add_Key_25px.png"))); // NOI18N
        bookRideButton4.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 57, 30));

        bookRideButton5.setBackground(new java.awt.Color(51, 0, 102));
        bookRideButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookRideButton5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bookRideButton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bookRideButton5MouseExited(evt);
            }
        });
        bookRideButton5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel36.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(240, 240, 240));
        jLabel36.setText("Schedule");
        bookRideButton5.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Bus_25px.png"))); // NOI18N
        bookRideButton5.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 57, 30));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(jLabel2))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 38, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bookRideButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(297, 297, 297)
                                .addComponent(removeVehicleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                            .addComponent(logOutButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(myRidesButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bookRideButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bookRideButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(bookRideButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(bookRideButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(bookRideButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(myRidesButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116)
                .addComponent(removeVehicleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(logOutButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 350, 646));

        jPanel6.setBackground(new java.awt.Color(153, 102, 255));

        jLabel38.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(204, 204, 204));
        jLabel38.setText("Welcome");

        welcome.setEditable(false);
        welcome.setBackground(new java.awt.Color(153, 102, 255));
        welcome.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        welcome.setForeground(new java.awt.Color(204, 204, 204));
        welcome.setBorder(null);
        welcome.setOpaque(false);
        welcome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                welcomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addGap(18, 18, 18)
                        .addComponent(welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(531, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 1030, 160));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(153, 153, 153));
        jLabel41.setText("Name");
        jPanel4.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 40, 20));

        jLabel42.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(153, 153, 153));
        jLabel42.setText("Father Name");
        jPanel4.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 70, 20));

        registerFather1.setEditable(false);
        registerFather1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        registerFather1.setForeground(new java.awt.Color(102, 102, 102));
        registerFather1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        jPanel4.add(registerFather1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, 160, -1));

        jLabel43.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(153, 153, 153));
        jLabel43.setText("Age");
        jPanel4.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 30, 20));

        registerAge1.setEditable(false);
        registerAge1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        registerAge1.setForeground(new java.awt.Color(102, 102, 102));
        registerAge1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        registerAge1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerAge1ActionPerformed(evt);
            }
        });
        jPanel4.add(registerAge1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 160, 20));

        jLabel45.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(153, 153, 153));
        jLabel45.setText("CNIC No");
        jPanel4.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, -1, -1));

        jLabel46.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(153, 153, 153));
        jLabel46.setText("Contact No");
        jPanel4.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 50, 20));

        registerName1.setEditable(false);
        registerName1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        registerName1.setForeground(new java.awt.Color(102, 102, 102));
        registerName1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        registerName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerName1ActionPerformed(evt);
            }
        });
        jPanel4.add(registerName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 160, 20));

        cnicText.setEditable(false);
        cnicText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cnicText.setForeground(new java.awt.Color(102, 102, 102));
        cnicText.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        jPanel4.add(cnicText, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 160, 20));

        contactnoText.setEditable(false);
        contactnoText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        contactnoText.setForeground(new java.awt.Color(102, 102, 102));
        contactnoText.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        contactnoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactnoTextActionPerformed(evt);
            }
        });
        jPanel4.add(contactnoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, 160, -1));

        changepassbtn.setBackground(new java.awt.Color(153, 51, 255));
        changepassbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changepassbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                changepassbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                changepassbtnMouseExited(evt);
            }
        });
        changepassbtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("EMAIL");
        changepassbtn.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText(" Save");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        changepassbtn.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        changepassbtn1.setBackground(new java.awt.Color(153, 51, 255));
        changepassbtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changepassbtn1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                changepassbtn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                changepassbtn1MouseExited(evt);
            }
        });
        changepassbtn1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("EMAIL");
        changepassbtn1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText(" Save");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        changepassbtn1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        changepassbtn.add(changepassbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, 160, 40));

        jPanel4.add(changepassbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, 160, 40));

        updatebtn.setBackground(new java.awt.Color(153, 51, 255));
        updatebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updatebtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updatebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updatebtnMouseExited(evt);
            }
        });
        updatebtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setText("EMAIL");
        updatebtn.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));

        jLabel23.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 204, 204));
        jLabel23.setText("Update Details");
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        updatebtn.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jPanel4.add(updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 590, 190, 40));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 102));
        jLabel7.setText("We Hope you're having a great day,");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 590, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 102));
        jLabel5.setText("Keep Vehling!");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 630, -1, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 670));

        jLabel47.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(153, 153, 153));
        jLabel47.setText("DOB");
        jPanel2.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1350, 670));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logOutButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutButtonMouseExited
        // TODO add your handling code here:
        logOutButton.setBackground(new Color(51,0,102));
    }//GEN-LAST:event_logOutButtonMouseExited

    private void logOutButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutButtonMouseEntered
        // TODO add your handling code here:
        logOutButton.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_logOutButtonMouseEntered

    private void logOutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutButtonMouseClicked
        // TODO add your handling code here:
        LoginMain lm=new LoginMain();
        this.setVisible(false);
        lm.setVisible(true);
    }//GEN-LAST:event_logOutButtonMouseClicked

    private void myRidesButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myRidesButtonMouseExited
        // TODO add your handling code here:
        myRidesButton.setBackground(new Color(51,0,102));
    }//GEN-LAST:event_myRidesButtonMouseExited

    private void myRidesButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myRidesButtonMouseEntered
        // TODO add your handling code here:
        myRidesButton.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_myRidesButtonMouseEntered

    private void myRidesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myRidesButtonMouseClicked
        // TODO add your handling code here:
        MyRidesd mr=new MyRidesd(idd);
        this.setVisible(false);
        mr.setVisible(true);
    }//GEN-LAST:event_myRidesButtonMouseClicked

    private void removeVehicleButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeVehicleButtonMouseExited
        // TODO add your handling code here:
        removeVehicleButton.setBackground(new Color(51,0,102));
    }//GEN-LAST:event_removeVehicleButtonMouseExited

    private void removeVehicleButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeVehicleButtonMouseEntered
        // TODO add your handling code here:
        removeVehicleButton.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_removeVehicleButtonMouseEntered

    private void addVehicleButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addVehicleButton5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_addVehicleButton5MouseExited

    private void addVehicleButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addVehicleButton5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_addVehicleButton5MouseEntered

    private void bookRideButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookRideButtonMouseExited
        // TODO add your handling code here:
        bookRideButton.setBackground(new Color(51,0,102));
    }//GEN-LAST:event_bookRideButtonMouseExited

    private void bookRideButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookRideButtonMouseEntered
        // TODO add your handling code here:
        bookRideButton.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_bookRideButtonMouseEntered

    private void bookRideButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookRideButtonMouseClicked
        // TODO add your handling code here:
     
     
       
    }//GEN-LAST:event_bookRideButtonMouseClicked

    private void bookRideButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookRideButton1MouseClicked
        // TODO add your handling code here:
        Currentrideact c=new Currentrideact(idd);
        this.setVisible(false);
        c.setVisible(true);
    }//GEN-LAST:event_bookRideButton1MouseClicked

    private void bookRideButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookRideButton1MouseEntered
        // TODO add your handling code here:
         bookRideButton1.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_bookRideButton1MouseEntered

    private void bookRideButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookRideButton1MouseExited
        // TODO add your handling code here:
         bookRideButton1.setBackground(new Color(51,0,102));
    }//GEN-LAST:event_bookRideButton1MouseExited

    private void bookRideButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookRideButton2MouseClicked
        // TODO add your handling code here:
        Scheduled s= new Scheduled(idd);
        this.setVisible(false);
        s.setVisible(true);
    }//GEN-LAST:event_bookRideButton2MouseClicked

    private void bookRideButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookRideButton2MouseEntered
        // TODO add your handling code here:
         bookRideButton2.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_bookRideButton2MouseEntered

    private void bookRideButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookRideButton2MouseExited
        // TODO add your handling code here:
         bookRideButton2.setBackground(new Color(51,0,102));
    }//GEN-LAST:event_bookRideButton2MouseExited

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        changepassbtn.action(null,null);
    }//GEN-LAST:event_jLabel16MouseClicked

     public String udata(String query, int idd,String name, String fname,String age,String cnic,String cn)
   {
   String sql=query;
    
     try
  {
 
      
      Connection1 cc=new Connection1();
      Connection con=cc.setconnectionD();
      Statement s=con.createStatement();
      CallableStatement stmt = con.prepareCall(query); 
     //stmt.registerOutParameter(1,OracleTypes.CURSOR);
     stmt.setInt(1,idd);
      stmt.setString(2, name);
      stmt.setString(3, fname);
       stmt.setString(4, age);
      stmt.setString(5, cnic);
    stmt.setString(6, cn);
      
            // run SP
            stmt.execute();
            return "ok";
//  ResultSet rs = (ResultSet) stmt.getObject(1);
//   table.setModel(DbUtils.resultSetToTableModel(rs));
//    System.out.println("Stored Procedure executed successfully");
  }
  catch(Exception err)
  {
    System.out.println("An error has occurred.");
    System.out.println("See full details below.");
    err.printStackTrace();
  
 
              JOptionPane.showMessageDialog(null, err);
              return "Error";
   }
   
   
   }  
    
    
    
    
    private void changepassbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changepassbtnMouseClicked
        // TODO add your handling code here:
        DriverCar p=new DriverCar();
       udata("{call uddata(?,?,?,?,?,?)}",idd,registerName1.getText(),registerFather1.getText(), registerAge1.getText(), cnicText.getText(), contactnoText.getText());
       getddata("{call getddata(?,?)}",idd);
        registerName1.setEditable(false);
        registerFather1.setEditable(false);
        registerAge1.setEditable(false);
        cnicText.setEditable(false);
        contactnoText.setEditable(false);
       // dob.setEditable(false);
     //   email.setEditable(false);
        welcome.setText(registerName1.getText());
        changepassbtn.hide();
     
    }//GEN-LAST:event_changepassbtnMouseClicked

    private void changepassbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changepassbtnMouseEntered
        // TODO add your handling code here:
        changepassbtn.setBackground(new Color(204,153,255));
    }//GEN-LAST:event_changepassbtnMouseEntered

    private void changepassbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changepassbtnMouseExited
        // TODO add your handling code here:
        changepassbtn.setBackground(new Color(153,51,255));
    }//GEN-LAST:event_changepassbtnMouseExited

    private void registerName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerName1ActionPerformed

    private void contactnoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactnoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactnoTextActionPerformed

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel23MouseClicked

    private void updatebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatebtnMouseClicked
        // TODO add your handling code here:
        changepassbtn.show();
    
      
        registerName1.setEditable(true);
        registerName1.grabFocus();
        registerFather1.setEditable(true);
        registerAge1.setEditable(true);
        cnicText.setEditable(true);
        contactnoText.setEditable(true);
    //    dob.setEditable(true);
    //    email.setEditable(true);
        
    }//GEN-LAST:event_updatebtnMouseClicked

    private void updatebtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatebtnMouseEntered
        // TODO add your handling code here:
         updatebtn.setBackground(new Color(204,153,255));
    }//GEN-LAST:event_updatebtnMouseEntered

    private void updatebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatebtnMouseExited
        // TODO add your handling code here:
         updatebtn.setBackground(new Color(153,51,255));
    }//GEN-LAST:event_updatebtnMouseExited

    private void bookRideButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookRideButton3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bookRideButton3MouseClicked

    private void bookRideButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookRideButton3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bookRideButton3MouseEntered

    private void bookRideButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookRideButton3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_bookRideButton3MouseExited

    private void addVehicleButton6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addVehicleButton6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_addVehicleButton6MouseEntered

    private void addVehicleButton6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addVehicleButton6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_addVehicleButton6MouseExited

    private void removeVehicleButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeVehicleButton1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_removeVehicleButton1MouseEntered

    private void removeVehicleButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeVehicleButton1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_removeVehicleButton1MouseExited

    private void myRidesButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myRidesButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_myRidesButton1MouseClicked

    private void myRidesButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myRidesButton1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_myRidesButton1MouseEntered

    private void myRidesButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myRidesButton1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_myRidesButton1MouseExited

    private void logOutButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_logOutButton1MouseClicked

    private void logOutButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutButton1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_logOutButton1MouseEntered

    private void logOutButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutButton1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_logOutButton1MouseExited

    private void bookRideButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookRideButton4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bookRideButton4MouseClicked

    private void bookRideButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookRideButton4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bookRideButton4MouseEntered

    private void bookRideButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookRideButton4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_bookRideButton4MouseExited

    private void bookRideButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookRideButton5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bookRideButton5MouseClicked

    private void bookRideButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookRideButton5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bookRideButton5MouseEntered

    private void bookRideButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookRideButton5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_bookRideButton5MouseExited

    private void registerAge1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerAge1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerAge1ActionPerformed

    private void welcomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_welcomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_welcomeActionPerformed

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel18MouseClicked

    private void changepassbtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changepassbtn1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_changepassbtn1MouseClicked

    private void changepassbtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changepassbtn1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_changepassbtn1MouseEntered

    private void changepassbtn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changepassbtn1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_changepassbtn1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(driverhomee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(driverhomee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(driverhomee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(driverhomee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new driverhomee().setVisible(true);
               
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addVehicleButton5;
    private javax.swing.JPanel addVehicleButton6;
    private javax.swing.JPanel bookRideButton;
    private javax.swing.JPanel bookRideButton1;
    private javax.swing.JPanel bookRideButton2;
    private javax.swing.JPanel bookRideButton3;
    private javax.swing.JPanel bookRideButton4;
    private javax.swing.JPanel bookRideButton5;
    private javax.swing.JPanel changepassbtn;
    private javax.swing.JPanel changepassbtn1;
    private javax.swing.JTextField cnicText;
    private javax.swing.JTextField contactnoText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JPanel logOutButton;
    private javax.swing.JPanel logOutButton1;
    private javax.swing.JPanel myRidesButton;
    private javax.swing.JPanel myRidesButton1;
    private javax.swing.JTextField registerAge1;
    private javax.swing.JTextField registerFather1;
    private javax.swing.JTextField registerName1;
    private javax.swing.JPanel removeVehicleButton;
    private javax.swing.JPanel removeVehicleButton1;
    private javax.swing.JPanel updatebtn;
    private javax.swing.JTextField welcome;
    // End of variables declaration//GEN-END:variables
}
